
  'name' => 'net.nemein.simpledb',
  'purecode' => false,
  'version' => '2.0.2beta1',
  'state' => 'beta',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'summary' => 'Simple web database',
    'description' => 'Simple web database utilizing datamanager schemas.',
    'maintainers' => 
    array (
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'lead',
      ),
      'rambo' => 
      array (
        'name' => 'Eero af Heurlin',
        'email' => 'eero.afheurlin@iki.fi',
        'role' => 'lead',
      ),
      'adrenalin' => 
      array (
        'name' => 'Arttu Manninen',
        'email' => 'arttu.manninen@protie.fi',
        'role' => 'developer',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
