array(
    'table' => 'net_nemein_attention_concept',
    'old_class_name' => null,
    'new_class_name' => 'net_nemein_attention_concept',
    'midcom_class_name' => 'net_nemein_attention_concept_dba'
),
array(
    'table' => 'net_nemein_attention_source',
    'old_class_name' => null,
    'new_class_name' => 'net_nemein_attention_source',
    'midcom_class_name' => 'net_nemein_attention_source_dba'
),