array(
    'table' => 'net_nemein_attention_concept',
    'mgdschema_class_name' => 'net_nemein_attention_concept',
    'midcom_class_name' => 'net_nemein_attention_concept_dba'
),
array(
    'table' => 'net_nemein_attention_source',
    'mgdschema_class_name' => 'net_nemein_attention_source',
    'midcom_class_name' => 'net_nemein_attention_source_dba'
),
array(
    'table' => 'net_nemein_attention_click',
    'mgdschema_class_name' => 'net_nemein_attention_click',
    'midcom_class_name' => 'net_nemein_attention_click_dba'
),