'name' => 'net.nemein.redirector',
'icon' => 'stock-icons/16x16/forward.png',
'purecode' => false,
'version' => '1.1.0beta1',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'summary' => 'Redirector',
    'description' => 'Folder that redirects to subnode or given URL',
    'maintainers' => array
    (
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
'state' => 'beta',
