'name' => 'net.nemein.redirector',
'purecode' => false,
'version' => '1.0.0',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(
    'summary' => 'Redirector',
    'description' => 'Folder that redirects to subnode or given URL',
    'maintainers' => Array(
        'bergie' => Array(
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
    ),
),
