/**
 * Schemadb path
 */
'schemadb_device' => 'file:/org/maemo/devcodes/config/schemadb_device_default.inc',
'schemadb_code' => 'file:/org/maemo/devcodes/config/schemadb_code_default.inc',
'schemadb_application' => 'file:/org/maemo/devcodes/config/schemadb_application_default.inc',

/**
 * Map area names to country names, key is area name value is array of
 * country names
 */
'area_country_map' => array(),
