array(
    'table' => 'org_maemo_devcodes_device',
    'old_class_name' => null,
    'new_class_name' => 'org_maemo_devcodes_device',
    'midcom_class_name' => 'org_maemo_devcodes_device_dba'
),
array(
    'table' => 'org_maemo_devcodes_code',
    'old_class_name' => null,
    'new_class_name' => 'org_maemo_devcodes_code',
    'midcom_class_name' => 'org_maemo_devcodes_code_dba'
),
array(
    'table' => 'org_maemo_devcodes_application',
    'old_class_name' => null,
    'new_class_name' => 'org_maemo_devcodes_application',
    'midcom_class_name' => 'org_maemo_devcodes_application_dba'
),
