'name' => 'org.openpsa.contactwidget',
'purecode' => true,
'privileges' =>  Array(),
'class_definitions' => Array(),
'version' => '2.0.3',
'state' => 'stable',
'package.xml' => Array(
    'summary' => 'Contact display widget',
    'description' => 'Widget for displaying person records in the hCard format',
    'maintainers' => Array(
        'bergie' => Array(
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),  
    ),
),
