
  'name' => 'org.openpsa.contactwidget',
  'purecode' => true,
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'version' => '2.0.5beta1',
  'state' => 'beta',
  'package.xml' => 
  array (
    'summary' => 'Contact display widget',
    'description' => 'Widget for displaying person records in the hCard format',
    'maintainers' => 
    array (
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'midcom' => 
      array (
      ),
    ),
  ),
