'name' => 'org.openpsa.contactwidget',
'icon' => 'org.openpsa.contactwidget/contact-widget-renderer.png',
'purecode' => true,
'privileges' => array(),
'class_definitions' => array(),
'version' => '2.1.0beta1',
'state' => 'beta',
'package.xml' => array
(
    'summary' => 'Contact display widget',
    'description' => 'Widget for displaying person records in the hCard format',
    'maintainers' => array
    (
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
