'name' => 'net.nemein.registrations',
'purecode' => false,
'version' => '0.1.7',
'privileges' => Array
(
    'manage' => MIDCOM_PRIVILEGE_DENY,
),
'class_definitions' => Array(),
'package.xml' => Array(
    'summary' => 'Event registration tool',
    'description' => 'This component allows you to provide your web site users a tool they can use to register for events you prepare for them.',
    'maintainers' => Array(
        'torben' => Array(
            'name' => 'Torben Nehmer',
            'email' => 'torben@nehmer.net',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
        'midcom.helper.datamanager' => Array(),
        'midcom.helper.datamanager2' => Array(),
    ),
),
