
  'name' => 'net.nemein.registrations',
  'purecode' => false,
  'version' => '0.1.10beta1',
  'state' => 'beta',
  'privileges' => 
  array (
    'manage' => MIDCOM_PRIVILEGE_DENY,
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'summary' => 'Event registration tool',
    'description' => 'This component allows you to provide your web site users a tool they can use to register for events you prepare for them.',
    'maintainers' => 
    array (
      'torben' => 
      array (
        'name' => 'Torben Nehmer',
        'email' => 'torben@nehmer.net',
        'role' => 'lead',
        'active' => 'no',
      ),
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'lead',
        'active' => 'yes',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager' => 
      array (
      ),
      'midcom.helper.datamanager2' => 
      array (
      ),
      'org.openpsa.mail' => 
      array (
      ),
      'net.nemein.calendar' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
