'schemadb' => 'file:/org/routamc/photostream/config/schemadb_default.inc',
'photos_per_page' => 20,

// Email API settings
'api_email_enable' => false,
'api_email_schema' => 'photo',
'api_email_default_tags' => 'moblog',

/* not implemented yet
'api_metaweblog_enable' => true,
'api_metaweblog_schema' => 'photo',
*/

// Flickr synchronization rules
'flickr_api_key' => 'f68bbf3e322b2f6cb487b7c50f003fea',
'flickr_import_size' => 'Large', // In some cases you want Original
