'name' => 'com.magnettechnologies.contactgrabber',
'purecode' => true,
'version' => '0.1.0beta1',
'state' => 'beta',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'license' => 'GPL',
    'summary' => 'Extensive package that can be used to grab user contact lists from the most important email and social networking sites: Rediff, Orkut, MySpace, Yahoo, Gmail and MSN Messenger.',
    'description' => 'Extensive package that can be used to grab user contact lists from the most important email and social networking sites: Rediff, Orkut, MySpace, Yahoo, Gmail and MSN Messenger.',
    'maintainers' => array
    (
        'juhana' => array
        (
            'name' => 'Juhana Hirvilahti',
            'email' => 'juhana@nemein.com',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => array(),
    ),
),
