"index_list_old" => 0,
"enable_details" => 1,
"title"          => "Events",
"schemadb"       => "file:/de/linkm/events/config/schemadb_default.inc",
"schemadbs"      => Array (
    "file:/de/linkm/events/config/schemadb_default.inc" => "Event Calender Default Schema Database",
),
"default_schema" => "events",
"sort_order"     => "extra2",
"sort_orders"    => Array (
    "extra2" => "By date",
    "title"  => "By Title",
),
"index_add_seconds_after_endtime" => 86400, //Add one day buffer after the end date
"create_name_from_title" => 0,  // Generate filenames for articles based on the title
"symlink_topic" => null,
