'page_size' => 10,
'welcome_ask_count' => 5,
'welcome_bid_count' => 5,
'index_to' => null,

'expiration_days' => 90,
'account_topic' => null,

'schemadb' => 'file:/net/nehmer/marketplace/config/schemadb_default.inc',
'categories' => Array('example 1', 'example 2', 'example 3', 'example 4|sub 1', 'example 4|sub 2', 'example 5', 'example 6'),

'ask_schema' => null,
'bid_schema' => null,

'mapping' => Array
(
    'default' => Array
    (
        'address' => 'street',
        'mobilephone' => 'handphone',
    ),
),