
"schemadb_article"       => "file:/midcom/admin/simplecontent/config/schemadb_article.inc",
"schemadb_topic"       => "file:/midcom/admin/simplecontent/config/schemadb_topic.inc",
"schemadbs"      => Array (
    "file:/midcom/admin/simplecontent/config/schemadb_article.inc" => "Article Schema Database",
    "file:/midcom/admin/simplecontent/config/schemadb_topic.inc" => "Topic schema database"
),


