
  'name' => 'midcom.admin.simplecontent',
  'purecode' => true,
  'version' => '0.0.2beta1',
  'state' => 'beta',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'license' => 'GPL',
    'maintainers' => 
    array (
      'tarjei' => 
      array (
        'name' => 'Tarjei Huse',
        'email' => 'tarjei@nu.no',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.admin.aegir' => 
      array (
      ),
      'no.bergfald.rcs' => 
      array (
      ),
      'midcom.helper.datamanager' => 
      array (
      ),
      'midcom.helper.datamanager2' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
