'name' => 'org.openpsa.helpers',
'purecode' => true,
'privileges' => array(),
'class_definitions' => array(),
'version' => '2.1.0beta1',
'state' => 'beta',
'package.xml' => array
(
    'summary' => 'OpenPsa helpers library',
    'description' => 'OpenPsa helpers for AJAX and workgroup filtering, and some common housekeeping tasks',
    'maintainers' => array
    (
        'rambo' => array
        (
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
            'active' => 'no',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
