array(
    'table' => 'net_nemein_netmon_host',
    'old_class_name' => null,
    'new_class_name' => 'net_nemein_netmon_host',
    'midcom_class_name' => 'net_nemein_netmon_host_dba'
),
array(
    'table' => 'net_nemein_netmon_hostgroup',
    'old_class_name' => null,
    'new_class_name' => 'net_nemein_netmon_hostgroup',
    'midcom_class_name' => 'net_nemein_netmon_hostgroup_dba'
),
array(
    'table' => 'net_nemein_netmon_hostgroup_member',
    'old_class_name' => null,
    'new_class_name' => 'net_nemein_netmon_hostgroup_member',
    'midcom_class_name' => 'net_nemein_netmon_hostgroup_member_dba'
),
