
  'name' => 'net.nehmer.publications',
  'version' => '0.1.2beta1',
  'class_definitions' => 
  array (
    0 => 'midcomdba.inc',
  ),
  'state' => 'beta',
  'package.xml' => 
  array (
    'summary' => 'Publication management system',
    'description' => 'Manages publicaitons in several (yet hard-corded and not DB-normalized) categories',
    'maintainers' => 
    array (
      'torben' => 
      array (
        'name' => 'Torben Nehmer',
        'email' => 'torben@nehmer.net',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager' => 
      array (
      ),
      'midcom.helper.datamanager2' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
