'name' => 'net.nehmer.publications',
'version' => '0.1.0',
'class_definitions' => Array('midcomdba.inc'),
'state' => 'devel',
'package.xml' => Array
(
    'summary' => 'Publication management system',
    'description' => 'Manages publicaitons in several (yet hard-corded and not DB-normalized) categories',
    'maintainers' => Array
    (
        'midgard' => Array
        (
            'name' => 'Torben Nehmer',
            'email' => 'torben@nehmer.net',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array
    (
        'midcom.helper.datamanager' => Array(),
        'midcom.helper.datamanager2' => Array(),
    ),
),

