array(
    'table' => 'net_nehmer_publications_entry_db',
    'old_class_name' => null,
    'new_class_name' => 'net_nehmer_publications_entry_db',
    'midcom_class_name' => 'net_nehmer_publications_entry'
),
array(
    'table' => 'net_nehmer_publications_categorymap_db',
    'old_class_name' => null,
    'new_class_name' => 'net_nehmer_publications_categorymap_db',
    'midcom_class_name' => 'net_nehmer_publications_categorymap'
),