array(
    'table' => 'org_openpsa_products_product',
    'mgdschema_class_name' => 'org_openpsa_products_product',
    'midcom_class_name' => 'org_openpsa_products_product_dba'
),
array(
    'table' => 'org_openpsa_products_product_group',
    'mgdschema_class_name' => 'org_openpsa_products_product_group',
    'midcom_class_name' => 'org_openpsa_products_product_group_dba'
),
array(
    'table' => 'org_openpsa_products_product_member',
    'mgdschema_class_name' => 'org_openpsa_products_product_member',
    'midcom_class_name' => 'org_openpsa_products_product_member_dba'
),