array(
    'table' => 'org_openpsa_products_product',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_products_product',
    'midcom_class_name' => 'org_openpsa_products_product_dba'
),
array(
    'table' => 'org_openpsa_products_product_group',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_products_product_group',
    'midcom_class_name' => 'org_openpsa_products_product_group_dba'
),
array(
    'table' => 'org_openpsa_products_product_member',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_products_product_member',
    'midcom_class_name' => 'org_openpsa_products_product_member_dba'
),
array(
    'table' => 'org_openpsa_products_businessarea',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_products_businessarea',
    'midcom_class_name' => 'org_openpsa_products_businessarea_dba'
),
array(
    'table' => 'org_openpsa_products_businessarea_member',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_products_businessarea_member',
    'midcom_class_name' => 'org_openpsa_products_businessarea_member_dba'
),