'name' => 'midcom.helper.reflector',
'purecode' => true,
'version' => '0.2.0beta2',
'state' => 'beta',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'summary' => 'MidCOM reflection helper',
    'description' => 'Contains helper methods for shortcutting common reflection based tasks',
    'maintainers' => array
    (
        'rambo' => array
        (
            'name' => 'Eero af Heurlin',
            'email' => 'rambo@nemein.com',
            'role' => 'lead',
        ),
    ),
),
