
  'name' => 'no.odindata.quickform2',
  'description' => 'Submit forms to email ',
  'purecode' => false,
  'version' => '0.0.7beta1',
  'state' => 'beta',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'summary' => 'Quickform module for mailing forms. ',
    'description' => 'Quickform module for mailing forms',
    'maintainers' => 
    array (
      'tarjei' => 
      array (
        'name' => 'Tarjei Huse',
        'email' => 'tarjei@nu.no',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager2' => 
      array (
      ),
      'midcom.helper.datamanager' => 
      array (
      ),
      'midcom' => 
      array (
      ),
      'Mail_SMTP' => array(),
    ),
  ),
