'name' => 'org.openpsa.calendarwidget',
'purecode' => true,
'privileges' =>  Array(),
'class_definitions' => Array(),
'version' => '2.0.1',
'state' => 'stable',
'package.xml' => Array(
    'summary' => 'Widget for drawing calendar views',
    'description' => 'Supports day, week and month views, with configurable slot sizes',
    'maintainers' => Array(
        'bergie' => Array(
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),  
    ),
),
