'name' => 'org.openpsa.jabber',
'icon' => 'stock-icons/16x16/im-jabber.png',
'purecode' => false,
'privileges' => array(),
'class_definitions' => array(),
'version' => '2.1.0beta1',
'state' => 'beta',
'package.xml' => array
(
    'summary' => 'Jabber applet viewer',
    'description' => 'Jabber applet viewer',
    'maintainers' => array
    (
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'org.openpsa.core' => array(),
        'org.openpsa.helpers' => array(),
        'midcom' => array(),
    ),
),
