'name' => 'org.openpsa.jabber',
'purecode' => false,
'privileges' =>  Array(),
'class_definitions' => Array(),
'version' => '2.0.0beta2',
'state' => 'beta',
'package.xml' => Array(
    'summary' => 'Jabber applet viewer',
    'description' => 'Jabber applet viewer',
    'maintainers' => Array(
        'bergie' => Array(
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),  
    ),
    'dependencies' => Array(
        'org.openpsa.core'          => Array(),
        'org.openpsa.helpers'       => Array(),        
    ),
),