// YOUR WINDGURU USER ID (IF YOU DO NOT REMEMBER YOUR ID, SEE YOUR SETTINGS PAGE ON WINDGURU.CZ)
'id_user' => 0, 

// DEFAULT LANGUAGE VERSION, possible values: http://www.windguru.cz/int/help_index.php?sec=distr
'lang' => 'en', 

'schemadb' => 'file:/pl/olga/windguru/config/schemadb_default.inc',
'schemadb_config' => 'file:/pl/olga/windguru/config/schemadb_config.inc',

'status' => array
(
	WG_STATUS_GFS,
	WG_STATUS_NWW3,
	WG_STATUS_NONE,
),