'frontpage_score_start' => 50,
'frontpage_score_hour_penalty' => 0.25,
'frontpage_limit_days' => 20,

'frontpage_show_main_items' => 3,
'frontpage_show_abstract_length' => 1000,

'frontpage_show_secondary_items' => 7,

'frontpage_show_area_latest' => false,
'frontpage_show_area_latest_items' => 2,
'frontpage_show_area_substyle' => '',

'bestof_items' => 10,

'archive_generation_topic' => null,
'archive_generation_substyle' => '',

'comments_enable' => true,
'comments_modifier' => 1.5,

'favourites_enable' => true,
'favourites_modifier' => 0.7,

'delicious_enable' => false,
'delicious_modifier' => 0.5,

'digg_enable' => true,
'digg_modifier' => 0.5,
'digg_modifier_comments' => 1.5, // Value of comment respective to value of a digg
'digg_apikey' => 'http://www.midgard-project.org/',

/**
 * Technorati API keys can be generated in http://technorati.com/developers/apikey.html
 *
 * It has to be noted that the default keys are for non-commercial use only and are limited to 500 queries a day.
 */
'technorati_enable' => false,
'technorati_modifier' => 0.8,
'technorati_apikey' => '', 