'comments_enable' => true,
'comments_modifier' => 1.0,

'favourites_enable' => true,
'favourites_modifier' => 0.7,

'delicious_enable' => true,
'delicious_modifier' => 0.5,

'digg_enable' => true,
'digg_modifier' => 0.5,
'digg_modifier_comments' => 1.5, // Value of comment respective to value of a digg
'digg_apikey' => 'http://www.midgard-project.org/',

/**
 * Technorati API keys can be generated in http://technorati.com/developers/apikey.html
 *
 * It has to be noted that the default keys are for non-commercial use only and are limited to 500 queries a day.
 */
'technorati_enable' => false,
'technorati_modifier' => 0.8,
'technorati_apikey' => '', 