  'name' => 'net.nemein.bannedwords',
  'purecode' => true,
  'privileges' => array (),
  'class_definitions' => array ('midcom_dba_classes.inc'),
  'version' => '0.0.1',
  'state' => 'beta',
  'package.xml' => array (
    'summary' => 'Library for searching banned words from content and usernames',
    'maintainers' => array (
      'juhana' => array (
        'name' => 'Juhana Hirvilahti',
        'email' => 'juhana@nemein.com',
        'role' => 'lead',
      ),
    ),
    'dependencies' => array (
      'midcom' => array (),
    ),
  ),
