'name' => 'org.maemo.calendar',
'purecode' => false,
'version' => '8.09.0',
'state' => 'stable',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'summary' => 'Maemo Community Calendar',
    'description' => 'Maemo Community Calendar',
    'maintainers' => array
    (
        'w_i' => array
        (
            'name' => 'Jerry Jalava',
            'email' => 'jerry@nemein.com',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => array(),
        'org.maemo.calendarwidget' => array(),
        'org.maemo.calendarpanel' => array(),
        'org.openpsa.calendar' => array(),
        'net.nehmer.buddylist' => array(),
        'net.nemein.tag' => array(),
    ),
),
