'name' => 'org.openpsa.qbpager',
'purecode' => true,
'privileges' => array(),
'class_definitions' => array(),
'version' => '1.1.0beta1',
'state' => 'beta',
'package.xml' => array
(
    'summary' => 'Paged Query-Builder library',
    'description' => 'Library for automatically splitting query builder results to multiple pages',
    'maintainers' => array
    (
        'rambo' => array
        (
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
        'midcom_helper_xsspreventer' => array(),
    ),
),
