'name' => 'org.openpsa.qbpager',
'purecode' => true,
'privileges' =>  Array(),
'class_definitions' => Array(),
'version' => '1.0.4',
'state' => 'stable',
'package.xml' => Array(
    'summary' => 'Paged Query Builder library',
    'description' => 'Library for automatically splitting query builder results to multiple pages',
    'maintainers' => Array(
        'rambo' => Array(
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
    ),
),
