array(
    'table' => 'net_nehmer_accounts_invites_invite',
    'old_class_name' => null,
    'new_class_name' => 'net_nehmer_accounts_invites_invite',
    'midcom_class_name' => 'net_nehmer_accounts_invites_invite_dba'
),
array(
    'table' => 'net_nehmer_account_karma',
    'old_class_name' => null,
    'new_class_name' => 'net_nehmer_account_karma',
    'midcom_class_name' => 'net_nehmer_account_karma_dba'
),