
  'name' => 'no.bergfald.rcs',
  'description' => 'Front and backend for a versioning library',
  'purecode' => true,
  'version' => '1.0.2beta1',
  'state' => 'beta',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'license' => 'GPL',
    'maintainers' => 
    array (
      'tarjei' => 
      array (
        'name' => 'Tarjei Huse',
        'email' => 'tarjei@nu.no',
        'role' => 'lead',
      ),
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'developer',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.xml' => 
      array (
      ),
      'org.openpsa.contactwidget' => 
      array (
      ),
      'Text_Diff' => 
      array (
        'channel' => 'pear.php.net',
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
