'name' => 'no.bergfald.rcs',
'description' => 'Front and backend for a versioning library',
'purecode' => true,
'version' => '0.9.0',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(  
    'license' => 'GPL',  
    'maintainers' => Array( 
        'tarjei' => Array(  
            'name' => 'Tarjei Huse',  
            'email' => 'tarjei@nu.no',  
            'role' => 'lead',  
        ),  
    ),  
    'dependencies' => Array(
        'midcom.helper.xml' => array(),
        'org.openpsa.contactwidget' => array(),
        'Text_Diff' => array(
            'channel' => 'pear.php.net',
        ),
    ),  
),
