array(
    'table' => 'grp',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_organization',
    'midcom_class_name' => 'org_openpsa_contacts_group_dba'
),
array(
    'table' => 'person',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_person',
    'midcom_class_name' => 'org_openpsa_contacts_person_dba'
),
array(
    'table' => 'net_nehmer_buddylist_entry_db',
    'old_class_name' => null,
    'new_class_name' => 'net_nehmer_buddylist_entry_db',
    'midcom_class_name' => 'org_openpsa_contacts_buddy_dba'
),