array(
    'table' => 'grp',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_organization',
    'midcom_class_name' => 'midcom_org_openpsa_organization'
),
array(
    'table' => 'person',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_person',
    'midcom_class_name' => 'midcom_org_openpsa_person'
),
array(
    'table' => 'net_nehmer_buddylist_entry_db',
    'old_class_name' => null,
    'new_class_name' => 'net_nehmer_buddylist_entry_db',
    'midcom_class_name' => 'org_openpsa_contacts_buddy'
),