'name' => 'org.openpsa.interviews',
'purecode' => false,
'version' => '0.0.1',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(
    'summary' => 'Interviews',
    'description' => 'Phone interview manager',
    'maintainers' => Array(
        'bergie' => Array(
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
        'midcom.helper.datamanager2' => Array(),
        'org.openpsa.contactwidget' => Array(),
        'org.openpsa.directmarketing' => Array(),
    ),
),
