'name' => 'pl.olga.tellafriend',
'icon' => 'stock-icons/16x16/stock_mail-send.png',
'purecode' => true,
'version' => '1.1.0beta1',
'privileges' => array(),
'state' => 'beta',
'package.xml' => array
(
    'summary' => 'Tell a friend',
    'description' => 'A library for \'notify a friend\' feature.',
    'maintainers' => array
    (
        'solt' => array
        (
            'name' => 'Marcin Sołtysiak',
            'email' => 'office@imedia.com.pl',
            'role' => 'lead',
            'active' => 'yes',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => array(),
        'org.openpsa.mail' => array(),
        'midcom' => array(),
    ),
),
