"visible"        => TRUE, // Is this topic visible?
"schemadb"       => "file:/net/nemein/bookmarks/config/schemadb_default.dat",
"index_list_old" => TRUE,
"enable_details" => TRUE,
"delicius"       => TRUE,
"count"          => 4,
"sort_order"     => "reverse created",
"create_name_from_title" => TRUE,  // Generate filenames for articles based on the title 

// Symlinking
"symlink_topic"  => null, /* Use the content from another topic instead of the current one. 
                           * Do not overwrite this except on a per-topic level!!! 
                           */
