'name' => 'midcom.helper.imagepopup',
'description' => 'A simple filelister and editor',
'purecode' => true,
'version' => '0.0.5',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(  
    'license' => 'GPL',  
    'maintainers' => Array( 
        'tarjei' => Array(  
            'name' => 'Tarjei Huse',  
            'email' => 'tarjei@nu.no',  
            'role' => 'lead',  
        ),  
    ),  
    'dependencies' => Array(
        'midcom.helper.datamanager2' => Array(
            'min' => '0.8.13',
        ),
        'JavaScript_Prototype'      => Array(
            'channel' => 'pearified.com',
        ),
    ),  
),
