
  'name' => 'midcom.helper.imagepopup',
  'description' => 'Image upload and insertion tool',
  'purecode' => true,
  'version' => '0.1.5beta1',
  'state' => 'beta',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'license' => 'GPL',
    'maintainers' => 
    array (
      'tarjei' => 
      array (
        'name' => 'Tarjei Huse',
        'email' => 'tarjei@nu.no',
        'role' => 'lead',
      ),
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'lead',
      ),
      'netblade' => 
      array (
        'name' => 'Oskari Kokko',
        'email' => 'oskari.kokko@nemein.com',
        'role' => 'developer',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager2' => 
      array (
        'min' => '0.8.16',
      ),
      'JavaScript_Prototype' => 
      array (
        'channel' => 'pearified.com',
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
