'name' => 'midgard.admin.sitegroup',
'purecode' => true,
'version' => '0.0.4',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(  
    'license' => 'GPL',  
    'maintainers' => Array( 
        'tarjei' => Array(  
            'name' => 'Tarjei Huse',  
            'email' => 'tarjei@nu.no',  
            'role' => 'lead',  
        ),  
    ),  
    'dependencies' => Array
    (
        'Console_Getargs' => Array
        (
            'channel' => 'pear.php.net',
        ),
    ),  
    
),
