'name' => 'midgard.admin.sitegroup',
'purecode' => true,
'version' => '1.1.0beta1',
'state' => 'beta',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'license' => 'GPL',
    'maintainers' => array
    (
        'tarjei' => array
        (
            'name' => 'Tarjei Huse',
            'email' => 'tarjei@nu.no',
            'role' => 'lead',
        ),
        'solt' => array
        (
            'name' => 'Marcin Sołtysiak',
            'email' => 'olga@olga.pl',
            'role' => 'developer',
        ),
    ),
    'dependencies' => array
    (
        'Console_Getargs' => array
        (
            'channel' => 'pear.php.net',
        ),
        'midcom' => array(),
    ),
),
