CREATE TABLE net_nemein_discussion_thread (
  id int(11) NOT NULL auto_increment,
  created varchar(255) NOT NULL default '',
  revisor int(11) NOT NULL default '0',
  title varchar(255) NOT NULL default '',
  node int(11) NOT NULL default '0',
  creator int(11) NOT NULL default '0',
  revised varchar(255) NOT NULL default '',
  name varchar(255) NOT NULL default '',
  views int(11) NOT NULL default '0',
  revision int(11) NOT NULL default '0',
  guid varchar(80) NOT NULL default '',
  sitegroup int(11) NOT NULL default '0',
  metadata_creator varchar(80) NOT NULL default '',
  metadata_created datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_revisor varchar(80) NOT NULL default '',
  metadata_revised datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_revision int(11) NOT NULL default '0',
  metadata_locker varchar(80) NOT NULL default '',
  metadata_locked datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_approver varchar(80) NOT NULL default '',
  metadata_approved datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_author varchar(80) NOT NULL default '',
  metadata_owner varchar(80) NOT NULL default '',
  metadata_schedule_start datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_schedule_end datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_hidden tinyint(1) default '0',
  metadata_nav_noentry tinyint(1) default '0',
  metadata_size int(11) NOT NULL default '0',
  posts int(11) default '0',
  latestpost int(11) default '0',
  latestposttime int(11) default '0',
  PRIMARY KEY  (id),
  KEY net_nemein_discussion_thread_guid_idx (guid),
  KEY net_nemein_discussion_thread_sitegroup_idx (sitegroup),
  KEY net_nemein_discussion_thread_node_idx (node),
  KEY net_nemein_discussion_thread_posts_idx (posts),
  KEY net_nemein_discussion_thread_latestpost_idx (latestpost)
);
CREATE TABLE net_nemein_discussion_post (
  id int(11) NOT NULL auto_increment,
  status int(11) NOT NULL default '0',
  created varchar(255) NOT NULL default '',
  revisor int(11) NOT NULL default '0',
  thread int(11) NOT NULL default '0',
  replyto int(11) NOT NULL default '0',
  sendername varchar(255) NOT NULL default '',
  content text NOT NULL default '',
  senderip varchar(255) NOT NULL default '',
  creator int(11) NOT NULL default '0',
  revised varchar(255) NOT NULL default '',
  subject varchar(255) NOT NULL default '',
  sender int(11) NOT NULL default '0',
  senderurl varchar(255) NOT NULL default '',
  senderemail varchar(255) NOT NULL default '',
  revision int(11) NOT NULL default '0',
  guid varchar(80) NOT NULL default '',
  sitegroup int(11) NOT NULL default '0',
  metadata_creator varchar(80) NOT NULL default '',
  metadata_created datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_revisor varchar(80) NOT NULL default '',
  metadata_revised datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_revision int(11) NOT NULL default '0',
  metadata_locker varchar(80) NOT NULL default '',
  metadata_locked datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_approver varchar(80) NOT NULL default '',
  metadata_approved datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_author varchar(80) NOT NULL default '',
  metadata_owner varchar(80) NOT NULL default '',
  metadata_schedule_start datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_schedule_end datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_hidden tinyint(1) default '0',
  metadata_nav_noentry tinyint(1) default '0',
  metadata_size int(11) NOT NULL default '0',
  PRIMARY KEY  (id),
  KEY net_nemein_discussion_post_guid_idx (guid),
  KEY net_nemein_discussion_post_sitegroup_idx (sitegroup),
  KEY net_nemein_discussion_post_thread_idx (thread),
  KEY net_nemein_discussion_post_replyto_idx (replyto)
);
