array(
    'table' => 'net_nemein_discussion_thread',
    'old_class_name' => null,
    'new_class_name' => 'net_nemein_discussion_thread',
    'midcom_class_name' => 'net_nemein_discussion_thread_dba'
),
array(
    'table' => 'net_nemein_discussion_post',
    'old_class_name' => null,
    'new_class_name' => 'net_nemein_discussion_post',
    'midcom_class_name' => 'net_nemein_discussion_post_dba'
),