  'name' => 'midcom.helper.search',
  'version' => '1.0.4beta1',
  'state' => 'beta',
  'purecode' => false,
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'summary' => 'Search tool',
    'description' => 'Front-end for the Lucene search engine',
    'maintainers' => 
    array (
      'torben' => 
      array (
        'name' => 'Torben Nehmer',
        'email' => 'torben@nehmer.net',
        'role' => 'lead',
        'active' => 'no',
      ),
      'tarjei' => 
      array (
        'name' => 'Tarjei Huse',
        'email' => 'tarjei@nu.no',
        'role' => 'lead',
        'active' => 'yes',
      ),
 
    ),
    'dependencies' => 
    array (
      'midcom' => 
      array (
      ),
      'http_request' =>
         array (
            'channel' => 'pear.php.net',
        ),
    ),
  ),
