'name' => 'midcom.helper.search',
'version' => '1.0.0', // Follow versioning from http://www.michelf.com/projects/php-markdown/
'state'   => 'stable',
'purecode' => false,
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(
    'summary' => 'Search tool',
    'description' => 'Front-end for the Lucene search engine',
    'maintainers' => Array(
        'torben' => Array(
            'name' => 'Torben Nehmer',
            'email' => 'torben@nehmer.net',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
    ),
),