
  'name' => 'midcom.helper.search',
  'version' => '1.0.3beta1',
  'state' => 'beta',
  'purecode' => false,
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'summary' => 'Search tool',
    'description' => 'Front-end for the Lucene search engine',
    'maintainers' => 
    array (
      'torben' => 
      array (
        'name' => 'Torben Nehmer',
        'email' => 'torben@nehmer.net',
        'role' => 'lead',
        'active' => 'no',
      ),
    ),
    'dependencies' => 
    array (
      'midcom' => 
      array (
      ),
    ),
  ),
