'master_event'         => null,   // Event under which all root events are placed
'schemadb'             => 'file:/cc/kaktus/exhibitions/config/schemadb_default.inc',

// Number of items in navigation
'navigation_items' => 10,
'show_pseudo_leaves' => true,

// Enable AJAX editing
'enable_ajax_editing' => true,

'schemadb_config'      => 'file:/cc/kaktus/exhibitions/config/schemadb_config.inc',