'name' => 'cc.kaktus.exhibitions',
'version' => '0.0.2',
'state'   => 'alpha',
'package.xml' => array
(
    'summary' => 'Exhibitions listing',
    'description' => 'Exhibitions listing is a component for handling exhibitions',
    'maintainers' => array
    (
        'adrenalin' => array
        (
            'name' => 'Arttu Manninen',
            'email' => 'arttu@kaktus.cc',
            'role' => 'lead',
            'active' => 'yes',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => Array(),
    ),
),
