'name' => 'cc.kaktus.exhibitions',
'version' => '0.1.0beta1',
'state' => 'beta',
'package.xml' => array
(
    'summary' => 'Exhibitions listing',
    'description' => 'Exhibitions listing is a component for handling exhibitions',
    'maintainers' => array
    (
        'adrenalin' => array
        (
            'name' => 'Arttu Manninen',
            'email' => 'arttu@kaktus.cc',
            'role' => 'lead',
            'active' => 'yes',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => array(),
    ),
),
