'name' => 'net.nemein.feedcollector',
'purecode' => false,
'version' => '8.09.0',
'state' => 'stable',
'privileges' => array(),
'class_definitions' => array
(
    'midcom_dba_classes.inc',
),
'package.xml' => array
(
    'summary' => 'Show index-pages of multiple n.n.blog-folders on one index-page',
    'description' => 'Show index-pages of multiple n.n.blog-folders on one index-page',
    'maintainers' => array
    (
        'netblade' => array
        (
            'name' => 'Oskari Kokko',
            'email' => 'oskari.kokko@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => array(),
        'midcom.helper.dm2config' => array(),
    ),
),
