'name' => 'net.nemein.feedcollector',
'purecode' => false,
'version' => '1.0.0beta1',
'state' => 'beta',
'privileges' => array(),
'class_definitions' => array('midcom_dba_classes.inc'),
'package.xml' => array
(
    'summary' => 'Show index-pages of multiple n.n.blog-folders on one index-page',
    'description' => 'Show index-pages of multiple n.n.blog-folders on one index-page',
    'maintainers' => array
    (
        'netblade' => array
        (
            'name' => 'Oskari Kokko',
            'email' => 'oskari.kokko@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array
    (
        'midcom.helper.datamanager2' => array(),
    ),
),


