array(
    'table' => 'net_nehmer_mail_mailbox_db',
    'mgdschema_class_name' => 'net_nehmer_mail_mailbox_db',
    'midcom_class_name' => 'net_nehmer_mail_mailbox'
),
array(
    'table' => 'net_nehmer_mail_mail_db',
    'mgdschema_class_name' => 'net_nehmer_mail_mail_db',
    'midcom_class_name' => 'net_nehmer_mail_mail'
),
/*array(
    'table' => 'net_nehmer_mail_relation_db',
    'mgdschema_class_name' => 'net_nehmer_mail_relation_db',
    'midcom_class_name' => 'net_nehmer_mail_relation'
),
array(
    'table' => 'net_nehmer_mail_status_db',
    'mgdschema_class_name' => 'net_nehmer_mail_status_db',
    'midcom_class_name' => 'net_nehmer_mail_status'
),*/