array(
    'table' => 'net_nehmer_mail_mailbox_db',
    'old_class_name' => null,
    'new_class_name' => 'net_nehmer_mail_mailbox_db',
    'midcom_class_name' => 'net_nehmer_mail_mailbox'
),
array(
    'table' => 'net_nehmer_mail_mail_db',
    'old_class_name' => null,
    'new_class_name' => 'net_nehmer_mail_mail_db',
    'midcom_class_name' => 'net_nehmer_mail_mail'
),
array(
    'table' => 'net_nehmer_mail_relation_db',
    'old_class_name' => null,
    'new_class_name' => 'net_nehmer_mail_relation_db',
    'midcom_class_name' => 'net_nehmer_mail_relation'
),