'name' => 'net.nemein.organizations',
'purecode' => false,
'version' => '1.0.0',
'state'   => 'stable',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(
    'summary' => 'Company displayer',
    'description' => 'Display and edit companies',
    'maintainers' => Array(
        'bergie' => Array(
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
        'midcom.helper.datamanager' => Array(),
    ),
),