'name' => 'fi.protie.navigation',
'version' => '1.1.0beta1',
'state' => 'beta',
'purecode' => true,
'package.xml' => Array
(
    'summary' => 'Dynamic navigation',
    'description' => 'Versatile class for drawing dynamically navigation elements according to user preferences.',
    'maintainers' => Array
    (
        'adrenalin' => Array
        (
            'name' => 'Arttu Manninen',
            'email' => 'arttu.manninen@protie.fi',
            'role' => 'lead',
        ),
        'tarjei' => Array
        (
            'name' => 'Tarjei Huse',
            'email' => 'tarjei@nu.no',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array
    (
    ),
),
