'name' => 'fi.hut.staticdumps',
'purecode' => true,
'version' => '0.1.6',
'state' => 'beta',
'privileges' => array (),
'class_definitions' => array (),
'package.xml' => array
(
    'license' => 'GPL',
    'summary' => 'Static dumps helper',
    'description' => 'Simplify some corner cases of making static dumps from website',
    'maintainers' => array
    (
        'rambo' => array
        (
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@nemein.com',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
