'name' => 'midcom.tests',
'Description' => 'Libary and frontend to run MidCOM unittests.',
'purecode' => false,
'version' => '0.1.0',
'privileges' =>  Array(),
'class_definitions' => Array(),


'package.xml' => Array(  
    'license' => 'GPL',  
    'maintainers' => Array( 
        'tarjei' => Array(  
            'name' => 'Tarjei Huse',  
            'email' => 'tarjei@nu.no',  
            'role' => 'lead',  
        ),  
    ),  
    'dependencies' => Array(
        'simpletest' => array()
    ),  
),
