
  'name' => 'org.openpsa.smslib',
  'purecode' => true,
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'version' => '1.0.4beta1',
  'state' => 'beta',
  'package.xml' => 
  array (
    'summary' => 'SMS sending library',
    'description' => 'Library for transmitting SMS messages through different gateways',
    'maintainers' => 
    array (
      'rambo' => 
      array (
        'name' => 'Eero af Heurlin',
        'email' => 'eero.afheurlin@iki.fi',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'midcom' => 
      array (
      ),
    ),
  ),
