'name' => 'org.openpsa.smslib',
'purecode' => true,
'privileges' =>  Array(),
'class_definitions' => Array(),
'version' => '1.0.2',
'state' => 'stable',
'package.xml' => Array(
    'summary' => 'SMS sending library',
    'description' => 'Library for transmitting SMS messages through different gateways',
    'maintainers' => Array(
        'rambo' => Array(
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
    ),
),