// Schema database to use
'schemadb' => 'file:/net/nehmer/static/config/schemadb_default.inc',
'schemadbs'      => Array
(
    'file:/net/nehmer/static/config/schemadb_default.inc' => 'Default Schema Database',
),

// A valid sort order usable with QB
'sort_order' => 'score',

// Generate a directory index if no index article is found?
'autoindex' => false,

// If not in autoindex mode, show the index article in NAP?
'indexinnav' => false,

// Automatically approve new articles ?
'auto_approve' => false,

// Use the content from another topic instead of the current one.
// Do not overwrite this except on a per-topic level!!!
'symlink_topic' => null,

// Set this to false if you want all users to have full control over URL names.
'simple_name_handling' => true,

// Set this to true if you want to enable on-site AJAX editing
'enable_ajax_editing' => false,