
  'name' => 'net.nehmer.static',
  'version' => '1.0.10beta1',
  'state' => 'beta',
  'package.xml' => 
  array (
    'summary' => 'Static article content display',
    'description' => 'Static content display component emulating regular directory of HTML files',
    'maintainers' => 
    array (
      'torben' => 
      array (
        'name' => 'Torben Nehmer',
        'email' => 'torben@nehmer.net',
        'role' => 'lead',
        'active' => 'no',
      ),
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'lead',
        'active' => 'yes',
      ),
      'adrenalin' => 
      array (
        'name' => 'Arttu Manninen',
        'email' => 'arttu@kaktus.cc',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager2' => 
      array (
      ),
      'midcom.helper.datamanager' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
