/**
 * This is just a sample of how you use this file if you want to 
 * create your own table to use with the module.
array(
    'table' => 'net_nehmer_mail_mailbox',
    'new_class_name' => 'net_nehmer_mail_mailbox_db',
    'table' => 'net_nehmer_mail_mailbox_db',
    'old_class_name' => null,
    'midcom_class_name' => 'net_nehmer_mail_mailbox'
),
array(
    'table' => 'net_nehmer_mail_mail_db',
    'old_class_name' => null,
    'new_class_name' => 'net_nehmer_mail_mail_db',
    'midcom_class_name' => 'net_nehmer_mail_mail'
),
**/
