// Schema database to use
'schemadb' => 'file:/net/nemein/quickpoll/config/schemadb_default.inc',
'schemadbs'      => Array
(
    'file:/net/nemein/quickpoll/config/schemadb_default.inc' => 'Default Schema Database',
),
'schema' => 'default',

'archive_enable' => true,
'show_navigation_pseudo_leaves' => true,   // Set this to false if you want to hide archive and feeds navigation items
'enable_anonymous' => true,

'lock_ip_address' => true,
'allow_multiple_votes' => false,

