
  'name' => 'net.nemein.quickpoll',
  'purecode' => false,
  'version' => '1.0.2beta2',
  'state' => 'beta',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
    0 => 'midcom_dba_classes.inc',
  ),
  'package.xml' => 
  array (
    'summary' => 'Quick voting component',
    'description' => 'Quick voting component',
    'maintainers' => 
    array (
      'netblade' => 
      array (
        'name' => 'Oskari Kokko',
        'email' => 'oskari.kokko@iki.fi',
        'role' => 'lead',
      ),
      'w_i' => 
      array (
        'name' => 'Jerry Jalava',
        'email' => 'jerry.jalava@gmail.com',
        'role' => 'developer',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager2' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
