CREATE TABLE net_nemein_quickpoll_option (
  id int(11) NOT NULL auto_increment,
  title varchar(255) NOT NULL default '',
  article int(11) NOT NULL default '0',
  votes int(11) NOT NULL default '0',
  revised varchar(255) NOT NULL default '',
  revision int(11) NOT NULL default '0',
  created varchar(255) NOT NULL default '',
  creator int(11) NOT NULL default '0',
  revisor int(11) NOT NULL default '0',
  guid varchar(80) NOT NULL default '',
  sitegroup int(11) NOT NULL default '0',
  metadata_creator varchar(80) NOT NULL default '',
  metadata_created datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_revisor varchar(80) NOT NULL default '',
  metadata_revised datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_revision int(11) NOT NULL default '0',
  metadata_locker varchar(80) NOT NULL default '',
  metadata_locked datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_approver varchar(80) NOT NULL default '',
  metadata_approved datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_owner varchar(80) NOT NULL default '',
  metadata_schedule_start datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_schedule_end datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_hidden tinyint(1) default '0',
  metadata_nav_noentry tinyint(1) default '0',
  metadata_size int(11) NOT NULL default '0',
  metadata_authors longtext NOT NULL default '',
  metadata_published datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_imported datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_exported datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_deleted tinyint(1) NOT NULL default '0',
  metadata_score int(11) NOT NULL default '0',
  PRIMARY KEY  (id),
  KEY net_nemein_quickpoll_option_guid_idx (guid),
  KEY net_nemein_quickpoll_option_sitegroup_idx (sitegroup),
  KEY net_nemein_quickpoll_option_article_idx (article),
  KEY net_nemein_quickpoll_option_title_idx (title(125))
);
CREATE TABLE net_nemein_quickpoll_vote (
  id int(11) NOT NULL auto_increment,
  user int(11) NOT NULL default '0',
  article int(11) NOT NULL default '0',
  selectedoption int(11) NOT NULL default '0',
  ip varchar(255) NOT NULL default '',
  revised varchar(255) NOT NULL default '',
  revision int(11) NOT NULL default '0',
  created varchar(255) NOT NULL default '',
  creator int(11) NOT NULL default '0',
  revisor int(11) NOT NULL default '0',
  guid varchar(80) NOT NULL default '',
  sitegroup int(11) NOT NULL default '0',
  metadata_creator varchar(80) NOT NULL default '',
  metadata_created datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_revisor varchar(80) NOT NULL default '',
  metadata_revised datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_revision int(11) NOT NULL default '0',
  metadata_locker varchar(80) NOT NULL default '',
  metadata_locked datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_approver varchar(80) NOT NULL default '',
  metadata_approved datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_owner varchar(80) NOT NULL default '',
  metadata_schedule_start datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_schedule_end datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_hidden tinyint(1) default '0',
  metadata_nav_noentry tinyint(1) default '0',
  metadata_size int(11) NOT NULL default '0',
  metadata_authors longtext NOT NULL default '',
  metadata_published datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_imported datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_exported datetime NOT NULL default '0000-00-00 00:00:00',
  metadata_deleted tinyint(1) NOT NULL default '0',
  metadata_score int(11) NOT NULL default '0',
  PRIMARY KEY  (id),
  KEY net_nemein_quickpoll_vote_guid_idx (guid),
  KEY net_nemein_quickpoll_vote_sitegroup_idx (sitegroup),
  KEY net_nemein_quickpoll_vote_article_idx (article),
  KEY net_nemein_quickpoll_vote_option_idx (selectedoption)
);

ALTER TABLE net_nemein_quickpoll_vote ADD COLUMN value int(11) NOT NULL default '0';
ALTER TABLE net_nemein_quickpoll_vote ADD COLUMN textvalue varchar(255) NOT NULL default '';