'name' => 'midcom.admin.controls.l10n',
'purecode' => false,
'version' => '1.0.0',
'state' => 'stable',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(
    'summary' => 'MidCOM localization tool',
    'description' => 'Tool for translating MidCOM components',
    'maintainers' => Array(
        'torben' => Array(
            'name' => 'Torben Nehmer',
            'email' => 'torben@nehmer.net',
            'role' => 'lead',
        ),
    ),
),