'schemadb_config' => 'file:/pl/olga/mnogosearch/config/schemadb_config.inc',

'dbaddr' =>    '',

'cache' => true,

'detectclones' =>true,

'trackquery' => true,

'crosswords' => true,

'pageresults' => 10,

'sortorder' => 'RPD',

'hlbeg' =>    '<font color="#000088"><b>',
'hlend' =>    '</b></font>',

'excerptsize' => 1024,

'excerptpadding' => 64,

'dateformat' => '%d %b %Y %X %Z',

'resultslimit' =>  1000,

