
  'name' => 'pl.olga.mnogosearch',
  'version' => '1.0.3beta1',
  'state' => 'beta',
  'package.xml' => 
  array (
    'summary' => 'Mnogosearch indexer frontend',
    'description' => 'Frontend to popular open source searching indexer. Based on legacy PHP frontend from http://www.mnogosearch.org/',
    'maintainers' => 
    array (
      'solt' => 
      array (
        'name' => 'Marcin Sołtysiak',
        'email' => 'office@imedia.com.pl',
        'role' => 'lead',
        'active' => 'yes',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager2' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
