'name' => 'net.nemein.repeathandler',
'icon' => 'stock-icons/16x16/stock_task-recurring.png',
'purecode' => true,
'version' => '1.1.0beta1',
'privileges' => array(),
'class_definitions' => array(),
'state' => 'beta',
'package.xml' => array
(
    'summary' => 'Handler for repeated events',
    'description' => 'A purecode class for creating repeated events',
    'maintainers' => array
    (
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
            'active' => 'yes',
        ),
        'adrenalin' => array
        (
            'name' => 'Arttu Manninen',
            'email' => 'arttu.manninen@protie.fi',
            'role' => 'developer',
            'active' => 'yes',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
