
  'name' => 'net.nemein.hourview2',
  'purecode' => false,
  'version' => '0.0.5beta1',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'summary' => 'Hour report approval tool',
    'description' => 'Tool for approving hour reports made in org.openpsa.projects',
    'maintainers' => 
    array (
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'org.openpsa.projects' => 
      array (
      ),
      'org.openpsa.mail' => 
      array (
      ),
      'org.openpsa.sales' => 
      array (
      ),
      'org.openpsa.notifications' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
  'state' => 'beta',
