"schemadb" => "file:/net/nemein/orders/config/schemadb_default.inc",
"schema_product" => "product",
"schema_order" => "order",

"admin_user" => null,
"admin_password" => null,

"root_order_event" => null,
"symlink_config_topic" => null,

"mailing_company_group" => null,

"currency_sign" => "&euro;",

"enable_payment_management" => false,
"enable_net_nemein_payment_integration" => false,

"shipping" => 0,