
  'name' => 'midcom.helper.datamanager',
  'purecode' => true,
  'version' => '2.5.7beta1',
  'state' => 'beta',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'summary' => 'Data abstraction and form rendering library',
    'description' => 'midcom.helper.datamanager is a MidCOM purecode component providing database abstraction and form processing features to MidCOM components.',
    'maintainers' => 
    array (
      'torben' => 
      array (
        'name' => 'Torben Nehmer',
        'email' => 'torben@nehmer.net',
        'role' => 'lead',
        'active' => 'no',
      ),
    ),
    'dependencies' => 
    array (
      'midcom' => 
      array (
      ),
    ),
  ),
