'name' => 'midcom.helper.datamanager',
'purecode' => true,
'version' => '2.5.3',
'state' => 'stable',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(
    'summary' => 'Data abstraction and form rendering library',
    'description' => 'midcom.helper.datamanager is a MidCOM purecode component providing database abstraction and form processing features to MidCOM components.',
    'maintainers' => Array(
        'midgard' => Array(
            'name' => 'The Midgard Project',
            'email' => 'dev@midgard-project.org',
            'role' => 'lead',
        ),
    ),
),
