/**
 * This is the configuration file for the module.
 * This is where you set default values for different configuration variables
 */
/* The sort order to use */
'sort_order' => 'score',

/* The schema database to use */
'schemadb' => 'file:/net/nemein/teams/config/schemadb_default.inc',

/* The schema in the database to use to edit articles 
 * note the name here and in schemadb_default.inc
 * This is used when having created the complete crud component - not just the basic one. 
 * */
'schema' => 'default',

'teams_root_guid' => 'bd153978547111dcbbc6cf47b1b3dd3fdd3f',
'create_team_home' => true,
