'name' => 'net.nemein.teams',
'purecode' => false,
'version' => '0.1.0beta1',
'state' => 'beta',
'privileges' => array(),
'class_definitions' => array
(
    'midcom_dba_classes.inc',
),
'package.xml' => array
(
    'summary' => 'Teams',
    'description' => 'Teams',
    'maintainers' => array
    (
        'juhana' => array
        (
            'name' => 'Juhana Hirvilahti',
            'email' => 'ihirvila@cc.hut.fi',
            'role' => 'lead',
            'active' => 'no',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => array(),
    ),
),
