array(
    'table' => 'net_nemein_teams_log',
    'mgdschema_class_name' => 'net_nemein_teams_log',
    'midcom_class_name' => 'net_nemein_teams_log_dba'
),
array(
    'table' => 'net_nemein_teams_team',
    'mgdschema_class_name' => 'net_nemein_teams_team',
    'midcom_class_name' => 'net_nemein_teams_team_dba'
),
array(
    'table' => 'net_nemein_teams_pending',
    'mgdschema_class_name' => 'net_nemein_teams_pending',
    'midcom_class_name' => 'net_nemein_teams_pending_dba'
),