
  'name' => 'org.openpsa.documents',
  'purecode' => false,
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
    0 => 'midcom_dba_classes.inc',
  ),
  'version' => '2.0.2beta1',
  'package.xml' => 
  array (
    'summary' => 'Document management',
    'description' => 'Organize and manage documents with metadata, search inside documents.',
    'maintainers' => 
    array (
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'org.openpsa.core' => 
      array (
      ),
      'org.openpsa.helpers' => 
      array (
      ),
      'midcom.helper.datamanager' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
  'state' => 'beta',
