array(
    'table' => 'org_openpsa_document',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_document',
    'midcom_class_name' => 'org_openpsa_documents_document'
),
array(
    'table' => 'org_openpsa_document_link_organization',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_document_link_organization',
    'midcom_class_name' => 'org_openpsa_document_link_organization_dba'
),