'name' => 'net.nemein.shoppingcart',
'purecode' => false,
'version' => '0.6.0beta1',
'state' => 'beta',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'summary' => 'Simple shopping cart',
    'description' => 'Shopping cart to use with the product database',
    'maintainers' => array
    (
        'rambo' => array
        (
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => array(),
        'org.openpsa.products' => array(),
        'org.openpsa.mail' => array(),
    ),
),
