
  'name' => 'net.nehmer.blog',
  'version' => '1.2.2beta1',
  'state' => 'beta',
  'package.xml' => 
  array (
    'summary' => 'Weblog system',
    'description' => 'System for displaying and managing news posts',
    'maintainers' => 
    array (
      'torben' => 
      array (
        'name' => 'Torben Nehmer',
        'email' => 'torben@nehmer.net',
        'role' => 'lead',
        'active' => 'no',
      ),
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'lead',
        'active' => 'yes',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager2' => 
      array (
      ),
      'net.nehmer.comments' => 
      array (
      ),
      'org.openpsa.mail' => 
      array (
      ),
      'net.nemein.rss' => 
      array (
      ),
      'XML_RPC' => 
      array (
        'channel' => 'pear.php.net',
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
