'name' => 'net.nehmer.blog',
'version' => '1.1.4',
'state' => 'stable',
'package.xml' => Array
(
    'summary' => 'Weblog system',
    'description' => 'System for displaying and managing news posts',
    'maintainers' => Array
    (
        'midgard' => Array
        (
            'name' => 'The Midgard Project',
            'email' => 'dev@midgard-project.org',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array
    (
        'midcom.helper.datamanager2' => Array(),
        'net.nehmer.comments' => Array(),
        'org.openpsa.mail' => Array(),
    ),
),

