'name' => 'org.maemo.calendarwidget',
'purecode' => true,
'version' => '0.1.0beta1',
'state' => 'beta',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'summary' => 'Community calendar for maemo platform',
    'description' => 'Community calendar for maemo platform',
    'maintainers' => array
    (
        'w_i' => array
        (
            'name' => 'Jerry Jalava',
            'email' => 'jerry.jalava@nemein.com',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
        'org.maemo.calendarpanel' => array(),
    ),
),
