'name' => 'fi.protie.host',
'version' => '0.0.1',
'state' => 'alpha',
'package.xml' => array
(
    'summary' => 'Host creation',
    'description' => 'Host creation',
    'maintainers' => array
    (
        'adrenalin' => array
        (
            'name' => 'Arttu Manninen',
            'email' => 'arttu@kaktus.cc',
            'role' => 'lead',
            'active' => 'yes',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => array(),
        'midcom' => array
        (
            'min' => '2.8.16',
        ),
    ),
),
