'name' => 'midgard.webdav.styles',
'purecode' => false,
'version' => '8.09.0',
'state' => 'stable',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'summary' => 'Webdav module for editing styles',
    'description' => 'Webdav module for editing styles',
    'maintainers' => array
    (
        'tarjei' => array
        (
            'name' => 'Tarjei Huse',
            'email' => 'tarjei@nu.no',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'HTTP_WebDAV_Server' => array
        (
            'channel' => 'pear.php.net',
        ),
        'midcom' => array(),
    ),
),
