'name' => 'midgard.admin.wizards',
'purecode' => false,
'version' => '1.2.0beta1',
'state' => 'beta',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'summary' => 'Midgard Site Wizard',
    'description' => 'Plugin-based Web shell for the Midgard Site Wizard',
    'maintainers' => array
    (
        'juhana' => array
        (
            'name' => 'Juhana Hirvilahti',
            'email' => 'ihirvila@cc.hut.fi',
            'role' => 'lead',
            'active' => 'no',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => array(),
        'org.openpsa.mail' => array(),
    ),
),
