'name' => 'midcom.helper.filesync',
'purecode' => true,
'version' => '0.0.2',
'state' => 'devel',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'summary' => 'Site template filesystem synchronization',
    'description' => 'Site template filesystem synchronization',
    'maintainers' => array
    (
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
    ),
),
