'sms_import_enable' => false,
'sms_import_ip' => null,
'smslib_api' => null, // tambur, clickatell or email2sms
'smslib_uri' => null,
'smslib_client_id' => null,
'smslib_user' => null,
'smslib_password' => null,
'smslib_from' => null,

'plazes_developer_key' => '4c637b4469bc11d13e73aa18a55ff6e6',

// By default we use OpenLayers with OpenStreetMap as this doesn't require API key
'map_provider' => 'openlayers', 
'map_api_key'  => '',

'yahoo_application_key' => 'fXM3gd3V34H6hqVeOgJEkFRTtvOvvJyVzeoXJ0CsoJZQYtPIFVD6ScwnbKIVoPMhbX5k',
