array(
    'table' => 'org_routamc_positioning_country',
    'mgdschema_class_name' => 'org_routamc_positioning_country',
    'midcom_class_name' => 'org_routamc_positioning_country_dba'
),
array(
    'table' => 'org_routamc_positioning_city',
    'mgdschema_class_name' => 'org_routamc_positioning_city',
    'midcom_class_name' => 'org_routamc_positioning_city_dba'
),
array(
    'table' => 'org_routamc_positioning_aerodrome',
    'mgdschema_class_name' => 'org_routamc_positioning_aerodrome',
    'midcom_class_name' => 'org_routamc_positioning_aerodrome_dba'
),
array(
    'table' => 'org_routamc_positioning_location',
    'mgdschema_class_name' => 'org_routamc_positioning_location',
    'midcom_class_name' => 'org_routamc_positioning_location_dba'
),
array(
    'table' => 'org_routamc_positioning_log',
    'mgdschema_class_name' => 'org_routamc_positioning_log',
    'midcom_class_name' => 'org_routamc_positioning_log_dba'
),