
  'name' => 'org.openpsa.relatedto',
  'purecode' => true,
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
    0 => 'midcom_dba_classes.inc',
  ),
  'version' => '1.0.5beta1',
  'state' => 'beta',
  'package.xml' => 
  array (
    'summary' => 'Library for handling "related to" links',
    'maintainers' => 
    array (
      'rambo' => 
      array (
        'name' => 'Eero af Heurlin',
        'email' => 'eero.afheurlin@iki.fi',
        'role' => 'lead',
      ),
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'developer',
      ),
    ),
    'dependencies' => 
    array (
      'org.openpsa.helpers' => 
      array (
      ),
      'org.openpsa.contactwidget' => 
      array (
      ),
      'JavaScript_Scriptaculous' => 
      array (
        'channel' => 'pearified.com',
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
