'name' => 'org.openpsa.relatedto',
'purecode' => true,
'privileges' =>  Array(),
'class_definitions' => Array('midcom_dba_classes.inc'),
'version' => '1.0.1',
'package.xml' => Array(
    'summary' => 'Library for handling "related to" links',
    'maintainers' => Array(
        'rambo' => Array(
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
        'org.openpsa.helpers'       => Array(),
        'org.openpsa.contactwidget' => Array(),
        'JavaScript_Scriptaculous'      => Array(
            'channel' => 'pearified.com',
        ),
    ),

),
