
'registry' => array (
    'ais'           => array (
        'component' => 'midcom.admin.content2',
        'name'      => 'Content editor',
        'hide'      => 0, 
    ),
    'simplecontent' => array (
        'component' => 'midcom.admin.simplecontent',
        'name'      => 'Topics and Articles',
        'hide'      => 0,
        ),
    'rcs'           => array (
        'component' => 'no.bergfald.rcs',
        'name'      => 'Version control',
        'hide'      => true,
    ),
    'objectbrowser' => array (
        'component' => 'no.bergfald.objectbrowser',
        'name'      => 'Objectbrowser',
        'hide'      => 0, 
    ),
    'tests'           => array (
        'component' => 'midcom.tests',
        'name'      => 'Midcom tests',
        'hide'      => 0, 
    ),  
    'styleeditor'           => array (
        'component' => 'midcom.admin.styleeditor',
        'name'      => 'Styles',
        'hide'      => 0, 
    ),  
    
),

'test_username' => 'tarjei',
'test_password' => 'tarjei',

