
  'name' => 'midcom.admin.aegir',
  'purecode' => false,
  'version' => '0.8.2beta1',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'customdata' => 
  array (
    'midcom.admin.aegir' => 
    array (
      'portal' => 
      array (
      ),
      'menu' => 
      array (
        'help' => 
        array (
          'url' => 'help/test',
          'text' => 'About Aegir',
        ),
        'portal' => 
        array (
          'url' => 'prefs',
          'text' => 'Preferences',
        ),
        'aegir' => 
        array (
          'url' => 'login/logout',
          'text' => 'Log out',
        ),
      ),
    ),
  ),
  'package.xml' => 
  array (
    'license' => 'GPL',
    'maintainers' => 
    array (
      'tarjei' => 
      array (
        'name' => 'Tarjei Huse',
        'email' => 'tarjei@nu.no',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager' => 
      array (
      ),
      'midcom.helper.datamanager2' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
  'state' => 'beta',
