"schemadb" => "file:/net/nemein/featured/config/schemadb_default.inc",
"schema_featured" => "featured",

"groups" => array(
    "info" => array(
        "title" => "Info",
	"description" => "Info featured",
        "root_object_guid" => "9822ff2c5acd11db845a197adaa843af43af",
	"default_substyles" => array(
            "midgard_topic" => "test_topic",
	    "midgard_article" => "test_article",
	),
	"accept_objects" => array(
            "midgard_topic",
	    "midgard_article",
	),
    ),
    "video" => array(
        "title" => "Video",
	"description" => "Video box",
	"root_object_guid" => "",
    ),
),
