"schemadb" => "file:/net/nemein/featured/config/schemadb_default.inc",

"groups" => array
(
    "info" => array
    (
        "title" => "Info",
        "description" => "Info featured",
        "default_substyles" => array
        (
            "midgard_topic" => "featured-topic",
            "midgard_article" => "featured-article",
        ),
        "accept_objects" => array
        (
            "midgard_topic",
            "midgard_article",
        ),
    ),
    "video" => array
    (
        "title" => "Video",
        "description" => "Video box",
        "default_substyles" => array
        (
            "ALL" => "",
        ),
    ),
),