'name' => 'net.nemein.featured',
'purecode' => false,
'version' => '0.1.0beta1',
'state' => 'beta',
'privileges' => array(),
'class_definitions' => array
(
    'midcom_dba_classes.inc',
),
'watches' => array(),
'package.xml' => array
(
    'license' => 'GPL',
    'summary' => 'Featured',
    'description' => 'Featured',
    'maintainers' => array
    (
        'juhana' => array
        (
            'name' => 'Juhana Hirvilahti',
            'email' => 'juhana@nemein.com',
            'role' => 'lead',
            'active' => 'no',
        ),
    ),
),
