'name'              => 'net.nemein.featured',
'purecode'          => false,
'version'           => '0.0.1',
'state'             => 'beta',
'privileges'        => Array(),
'class_definitions' => Array('midcom_dba_classes.inc'),
'watches'           => Array(),
'package.xml' => Array
(  
    'license' => 'GPL', 
    'summary' => 'Featured',
    'description' => 'Featured',
    'maintainers' => Array
    ( 
        'juhana' => Array
        (  
	    'name' => 'Juhana Hirvilahti',  
	    'email' => 'juhana@nemein.com',  
	    'role' => 'lead',  
	 ),  
     ),
),
