CREATE TABLE net_fernmark_pedigree_dog (
  id int(11) NOT NULL auto_increment,
  sitegroup int(11) NOT NULL default 0,
  node int(11) NOT NULL default 0,
  dam int(11) NOT NULL default 0,
  sire int(11) NOT NULL default 0,
  sex int(2) NOT NULL default 0,
  breed varchar(255) NOT NULL default '',
  dob datetime NOT NULL default '0000-00-00 00:00:00',
  tod datetime NOT NULL default '0000-00-00 00:00:00',
  name varchar(255) NOT NULL default '',
  regno varchar(255) NOT NULL default '',
  titles varchar(255) NOT NULL default '',
  notes longtext NOT NULL default '',
  owner int(11) NOT NULL default 0,
  breeder int(11) NOT NULL default 0,
  kennel int(11) NOT NULL default 0,
# other fields/indexes as ALTER TABLE statements
  PRIMARY KEY  (id),
  KEY net_fernmark_pedigree_dog_sitegroup_idx (sitegroup),
  KEY net_fernmark_pedigree_dog_node_idx (node),
  KEY net_fernmark_pedigree_dog_dam_idx (dam),
  KEY net_fernmark_pedigree_dog_sire_idx (sire),
  KEY net_fernmark_pedigree_dog_breed_idx (`breed`(30)),
  KEY net_fernmark_pedigree_dog_dob_idx (dob),
  KEY net_fernmark_pedigree_dog_tod_idx (tod),
  KEY net_fernmark_pedigree_dog_name_idx (`name`(30)),
  KEY net_fernmark_pedigree_dog_regno_idx (`regno`(30)),
  KEY net_fernmark_pedigree_dog_owner_idx (owner),
  KEY net_fernmark_pedigree_dog_breeder_idx (breeder),
  KEY net_fernmark_pedigree_dog_kennel_idx (kennel)
);
CREATE TABLE net_fernmark_pedigree_dog_result (
  id int(11) NOT NULL auto_increment,
  sitegroup int(11) NOT NULL default 0,
  dog int(11) NOT NULL default 0,
  `date` datetime NOT NULL default '0000-00-00 00:00:00',
  eventname varchar(255) NOT NULL default '',
  judge int(11) NOT NULL default 0,
  result varchar(255) NOT NULL default '',
  critique longtext NOT NULL default '',
# other fields/indexes as ALTER TABLE statements
  PRIMARY KEY  (id),
  KEY net_fernmark_pedigree_dog_result_sitegroup_idx (sitegroup),
  KEY net_fernmark_pedigree_dog_result_dog_idx (dog),
  KEY net_fernmark_pedigree_dog_date_idx (`date`),
  KEY net_fernmark_pedigree_dog_eventname_idx (`eventname`(30)),
  KEY net_fernmark_pedigree_dog_result_judge_idx (judge)
);
