array(
    'table' => 'net_fernmark_pedigree_dog',
    'old_class_name' => null,
    'new_class_name' => 'net_fernmark_pedigree_dog',
    'midcom_class_name' => 'net_fernmark_pedigree_dog_dba'
),
array(
    'table' => 'net_fernmark_pedigree_dog_result',
    'old_class_name' => null,
    'new_class_name' => 'net_fernmark_pedigree_dog_result',
    'midcom_class_name' => 'net_fernmark_pedigree_dog_result_dba'
),
