'name' => 'midgard.admin.sitewizard',
'purecode' => false,
'version' => '2.0.0alpha',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array
(
    'summary' => 'Site creation wizard',
    'description' => 'Tool for creating companies, sites and styles',
    'maintainers' => Array
    (
        'bergie' => Array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
        'w_i' => Array
        (
            'name' => 'Jerry Jalava',
            'email' => 'jerry.jalava@incognito.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array
    (
        'midgard.admin.sitegroup' => Array(),
    ),
),
