array(
    'table' => 'event',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_event',
    'midcom_class_name' => 'midcom_org_openpsa_event'
),
array(
    'table' => 'eventmember',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_eventmember',
    'midcom_class_name' => 'midcom_org_openpsa_eventmember'
),
array(
    'table' => 'org_openpsa_calendar_resource',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_calendar_resource',
    'midcom_class_name' => 'org_openpsa_calendar_resource_dba'
),
array(
    'table' => 'org_openpsa_calendar_event_resource',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_calendar_event_resource',
    'midcom_class_name' => 'org_openpsa_calendar_event_resource_dba'
),