
  'name' => 'de.linkm.sitemap',
  'description' => 'Automatic sitemap',
  'purecode' => false,
  'version' => '1.1.6beta1',
  'state' => 'beta',
  'package.xml' => 
  array (
    'summary' => 'Automatic site map',
    'description' => 'Automatically generate map of the website',
    'maintainers' => 
    array (
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'lead',
      ),
      'torben' => 
      array (
        'name' => 'Torben Nehmer',
        'email' => 'torben@nehmer.net',
        'role' => 'lead',
        'active' => 'no',
      ),
      'netblade' => 
      array (
        'name' => 'Oskari Kokko',
        'email' => 'oskari.kokko@nemein.com',
        'role' => 'developer',
      ),
      'adrenalin' => 
      array (
        'name' => 'Arttu Manninen',
        'email' => 'arttu.manninen@protie.fi',
        'role' => 'developer',
      ),
    ),
    'dependencies' => 
    array (
      'midcom' => 
      array (
      ),
    ),
  ),
