'name' => 'de.linkm.sitemap',
'version' => '1.0.0',
'state' => 'stable',
'package.xml' => Array
(
    'summary' => 'Automatic site map',
    'description' => 'Automatically generate map of the website',
    'maintainers' => Array
    (
        'torben' => Array
        (
            'name' => 'Torben Nehmer',
            'email' => 'torben@nehmer.net',
            'role' => 'lead',
        ),
    ),
),
