
'schemadb' => 'file:/no/odindata/quickform/config/schemadb_default.inc',
'schemadbs'      => Array
(
    'file:/no/odindata/quickform/config/schemadb_default.inc' => 'Default Schema Database',
),
'form_user' => null,
'form_pass' => null,

'mail' => true,
'mail_address_from' => '',
'mail_address_to' => '',
'mail_reply_to' => '',
'mail_subject' => '',
'mail_encoding' => 'UTF-8',
'mail_submitter' => false,
'end_message'  => '',
'mail_submitter_message' => '',
'form_description' => '',
'mail_reciept' => false,
'mail_reciept_message' => '',
'mail_reciept_data' => '',

'save_form_as_article' => false,
'mail_new_item' => true,


// Keep the additional empty lines below this for safeties sake

