
"schemadb" => "file:/no/odindata/quickform/config/schemadb_default.inc",
"form_user" => null,
"form_pass" => null,

"mail" => true,
"mail_address_from" => '',
"mail_address_to" => "",
"mail_subject" => "",
"mail_encoding" => "UTF-8",
"mail_submitter" => false,
"end_message"  => '',
"mail_submitter_message" => "",
"form_description" => "",
'mail_reciept' => false,
"mail_reciept_message" => '',
"mail_reciept_data" => '',


// Keep the additional empty lines below this for safeties sake

