'name' => 'no.odindata.quickform',
'description' => 'A simple email form generator',
'purecode' => false,
'version' => '1.3',
'state' => 'stable',
'privileges' => array (),
'class_definitions' => array (),
'package.xml' => array (
    'license' => 'GPL',
    'maintainers' => array
    (
        'tarjei' => array
        (
            'name' => 'Tarjei Huse',
            'email' => 'tarjei@nu.no',
            'role' => 'lead',
        ),
        'jbergius' => array
        (
            'name' => 'Joonas Bergius',
            'email' => 'joonas.bergius@gmail.com',
            'role' => 'developer',
        ),
        'adrenalin' => array
        (
            'name' => 'Arttu Manninen',
            'email' => 'arttu.manninen@protie.fi',
            'role' => 'developer',
        ),
        'netblade' => array
        (
            'name' => 'Oskari Kokko',
            'email' => 'oskari.kokko@iki.fi',
            'role' => 'developer',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager' => array (),
        'org.openpsa.mail' => array (),
        'midcom' => array (),
    ),
),
