'name' => 'no.odindata.quickform',
'description' => "A simple email form generator",
'purecode' => false,
'version' => '0.1.1',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(  
    'license' => 'GPL',  
    'maintainers' => Array( 
        'tarjei' => Array(  
            'name' => 'Tarjei Huse',  
            'email' => 'tarjei@nu.no',  
            'role' => 'lead',  
        ),  
    ),  
    'dependencies' => Array(
    'midcom.helper.datamanager' => Array(),
    ),  
),
