
  'name' => 'org.openpsa.queries',
  'purecode' => true,
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
    0 => 'midcom_dba_classes.inc',
  ),
  'version' => '1.0.5beta1',
  'state' => 'beta',
  'package.xml' => 
  array (
    'summary' => 'Library for stored queries',
    'description' => 'Library for handling stored QB queries',
    'maintainers' => 
    array (
      'rambo' => 
      array (
        'name' => 'Eero af Heurlin',
        'email' => 'eero.afheurlin@iki.fi',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'midcom' => 
      array (
      ),
    ),
  ),
