'name' => 'org.openpsa.queries',
'purecode' => true,
'privileges' =>  Array(),
'class_definitions' => Array('midcom_dba_classes.inc'),
'version' => '1.0.2',
'state' => 'stable',
'package.xml' => Array(
    'summary' => 'Library for stored queries',
    'description' => 'Library for handling stored QB queries',
    'maintainers' => Array(
        'rambo' => Array(
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
    ),
),
