array(
    'table' => 'net_nehmer_branchenbuch_branche_db',
    'old_class_name' => null,
    'new_class_name' => 'net_nehmer_branchenbuch_branche_db',
    'midcom_class_name' => 'net_nehmer_branchenbuch_branche'
),
array(
    'table' => 'net_nehmer_branchenbuch_entry_db',
    'old_class_name' => null,
    'new_class_name' => 'net_nehmer_branchenbuch_entry_db',
    'midcom_class_name' => 'net_nehmer_branchenbuch_entry'
),