'createbranche' => Array
(
    'description' => 'createbranche',
    'operations' => Array
    (
        'save' => 'createbranche: save and return',
        'next' => 'createbranche: save and add more',
        'cancel' => '',
    ),
    'fields' => Array
    (
        'name' => Array
        (
            'title' => 'name',
            'description' => '',
            'helptext' => '',

            'storage' => 'name',
            'required' => true,
            'type' => 'text',
            'widget' => 'text',
        ),
    ),
),
'editbranche' => Array
(
    'description' => 'editbranche',
    'fields' => Array
    (
        'name' => Array
        (
            'title' => 'name',
            'description' => '',
            'helptext' => '',

            'storage' => 'name',
            'required' => true,
            'type' => 'text',
            'widget' => 'text',
        ),
    ),
),