'name' => 'midcom.admin.core',
'description' => 'This purecode module defines what onsite editing commands exist.',
'purecode' => true,
'version' => '0.8.0',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(  
    'license' => 'GPL',  
    'maintainers' => Array( 
        'tarjei' => Array(  
            'name' => 'Tarjei Huse',  
            'email' => 'tarjei@nu.no',  
            'role' => 'lead',  
        ),  
    ),  
    'dependencies' => Array(
    ),  
),
