'name' => 'midcom.admin.libconfig',
'description' => 'Library configuration tool',
'purecode' => true,
'version' => '0.1.0beta1',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'license' => 'LGPL',
    'maintainers' => array
    (
        'solt' => array
        (
            'name' => 'Marcin Sołtysiak',
            'email' => 'olga@olga.pl',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom.admin.help',
        'midcom' => array(),
    ),
),
'state' => 'beta',
'customdata' => array(),
