
  'name' => 'midcom.admin.libconfig',
  'description' => 'Library configuration tool',
  'purecode' => true,
  'version' => '0.0.1alpha',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'license' => 'LGPL',
    'maintainers' => 
    array (
      'solt' => 
      array (
        'name' => 'Marcin Sołtysiak',
        'email' => 'olga@olga.pl',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      0 => 'midcom.admin.help',
      'midcom' => 
      array (
      ),
    ),
  ),
  'state' => 'alpha',
  'customdata' => array
  (
      /*'asgard_plugin' => array
      (
          'class' => 'midcom_admin_libconfig_plugin',
          'src' => 'file:/midcom/admin/libconfig/plugin.php',
          'name' => 'midcom.admin.libconfig',
          'config' => null,
      ),*/
  ),
