
  'name' => 'net.nemein.internalorders',
  'purecode' => false,
  'version' => '1.0.2beta1',
  'privileges' => 
  array (
  ),
  'package.xml' => 
  array (
    'summary' => 'Internal orders',
    'description' => 'Internal orders tool for Anttila',
    'maintainers' => 
    array (
      'netblade' => 
      array (
        'name' => 'Oskari Kokko',
        'email' => 'oskari.kokko@nemein.com',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager2' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
  'state' => 'beta',
