
  'name' => 'org.openpsa.expenses',
  'purecode' => false,
  'version' => '0.0.3beta1',
  'state' => 'beta',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'summary' => 'Expense tracking',
    'description' => 'Tracking of work hours, expenses and mileages',
    'maintainers' => 
    array (
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'org.openpsa.projects' => 
      array (
      ),
      'midcom.helper.datamanager2' => 
      array (
      ),
      'Calendar' => 
      array (
        'channel' => 'pear.php.net',
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
