'name' => 'net.nemein.wiki',
'purecode' => false,
'version' => '2.0.4',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(
    'summary' => 'Wiki',
    'description' => 'Wiki online notebook',
    'maintainers' => Array(
        'bergie' => Array(
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
        'midcom.helper.datamanager2' => Array(),
        'de.bitfolge.feedcreator' => Array(),
        'no.bergfald.rcs' => Array(),
        'org.openpsa.relatedto' => Array(),
        'org.openpsa.contactwidget' => Array(),
    ),
),
