'name' => 'midcom.helper.xml',
'purecode' => true,
'version' => '1.1.0beta1',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'license' => 'GPL',
    'maintainers' => array
    (
        'tarjei' => array
        (
            'name' => 'Tarjei Huse',
            'email' => 'tarjei@nu.no',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
'state' => 'beta',
