'name' => 'midcom.helper.xml',
'purecode' => true,
'version' => 1,
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(  
    'license' => 'GPL',  
    'maintainers' => Array( 
        'tarjei' => Array(  
            'name' => 'Tarjei Huse',  
            'email' => 'tarjei@nu.no',  
            'role' => 'lead',  
        ),  
    ),  
    'dependencies' => Array(
    ),  
),
