'name' => 'net.nemein.calendar',
'purecode' => false,
'version' => '1.0.3',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(
    'summary' => 'Event calendar',
    'description' => 'Event calendar',
    'maintainers' => Array(
        'bergie' => Array(
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
        'net.nemein.repeathandler' => Array(),
    ),
),
