'name' => 'net.nehmer.markdown',
'version' => '1.0.1', // Follow versioning from http://www.michelf.com/projects/php-markdown/
'state'   => 'stable',
'purecode' => true,
'package.xml' => Array(
    'summary' => 'Markdown formatter',
    'description' => 'PHP Markdown is a port to PHP of the Markdown program written by John Gruber.',
    'maintainers' => Array(
        'torben' => Array(
            'name' => 'Torben Nehmer',
            'email' => 'torben@nehmer.net',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
    ),
),