<?php

/**
  * Contact Grabber
  * Version 1.0
  * Released 9th May, 2007
  * Author: Magnet Technologies, vishal.kothari@magnettechnologies.com
  * Credits: Janak Prajapati, Pravin Shukla, Tapan Moharana
  * Copyright (C) 2007

  * This program is free software; you can redistribute it and/or
  * modify it under the terms of the GNU General Public License
  * as published by the Free Software Foundation; either version 2
  * of the License, or (at your option) any later version.

  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.

  * You should have received a copy of the GNU General Public License
  * along with this program; if not, write to the Free Software
  * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
  **/

require_once('class.GrabYahoo.php');
require_once('./config.php');

// Yahoo! Account Username
$login    = $_POST['username']."@".$_POST['domain'];

// Yahoo! Account Password
$password = $_POST['password'];

// Initializing Class
$yahoo  = new GrabYahoo;

/* 
Setting the desired Service 
  1. addressbook => Used to grab Yahoo! Address Book
  2. messenger => Used to grab Yahoo! Messenger List
  3. newmail => Used to grab number of new Yahoo! mails
*/
$yahoo->service = "addressbook";

/*
Set to true if HTTP proxy is required to browse net
  - Setting it to true will require to provide Proxy Host Name and Port number
*/
$yahoo->isUsingProxy = false;

// Set the Proxy Host Name, isUsingProxy is set to true
$yahoo->proxyHost = "";

// Set the Proxy Port Number
$yahoo->proxyPort = "";

// Set the location to save the Cookie Jar File
//$yahoo->cookieJarPath = $_SERVER['DOCUMENT_ROOT'] . "/yahoo/";
$yahoo->cookieJarPath = $DIR_PATH."/tmp/";

/* 
Execute the Service 
  - Require to pass Yahoo! Account Username and Password
*/
$yahooList = $yahoo->execService($login, $password);

if(is_array($yahooList))
{
	// Printing the array generated by the Class
	echo "<table border='1'>
	<tr><td align='center'><b>Name</b></td><td align='center'><b>Email Address</b></td></tr>";
	for($i=0;$i<=count($yahooList);$i++)
	{
	      //echo "<pre>";
	      $store=$yahooList[$i];
	      $name=$store["First Name"];
	      $nam=str_replace("<br>","",$name);
	      $email=$store["E-mail Address"];
	      $emal=str_replace("<br>","",$email);
	      if($nam!="")
	      {
	      //echo "name :";
	      print("<tr><td style='Font-Family:verdana;Font-Size:14'>$nam</td>");
	      //echo "<br>";
	      }
	       elseif($nam=="" &&  $emal!="")
	       {
	        print("<tr><td>&nbsp;</td>");
	       }
	      $emal=str_replace("<br>","",$email);
	      if($emal!="")
	      {
	      print("<td style='Font-Family:verdana;Font-Size:14'>$emal</td></tr>");
	      }
	      elseif($nam!="")
	      {
	      print("<td>&nbsp;</td></tr>");
	      }
	}
}
echo $yahoo->errorInfo;



?>
