'rounding_precision' => 1,

'schemadb_log' => 'file:/fi/protie/garbagetruck/config/schemadb_log.inc',
'schemadb_area' => 'file:/fi/protie/garbagetruck/config/schemadb_area.inc',
'schemadb_route' => 'file:/fi/protie/garbagetruck/config/schemadb_route.inc',
'schemadb_query' => 'file:/fi/protie/garbagetruck/config/schemadb_query.inc',
'schemadb_person' => 'file:/fi/protie/garbagetruck/config/schemadb_person.inc',
'schemadb_vehicle' => 'file:/fi/protie/garbagetruck/config/schemadb_vehicle.inc',
