
  'name' => 'fi.protie.garbagetruck',
  'purecode' => false,
  'version' => '1.1.3beta1',
  'state' => 'beta',
  'class_definitions' => 
  array (
    0 => 'midcom_dba_classes.inc',
  ),
  'package.xml' => 
  array (
    'summary' => 'Statistics for garbagetrucks',
    'description' => 'Statistics tool for garbagetrucks',
    'maintainers' => 
    array (
      'adrenalin' => 
      array (
        'name' => 'Arttu Manninen',
        'email' => 'arttu.manninen@protie.fi',
        'role' => 'lead',
        'active' => 'yes',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager2' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
