array
(
    'table' => 'fi_protie_garbagetruck_area',
    'old_class_name' => null,
    'new_class_name' => 'fi_protie_garbagetruck_area_db',
    'midcom_class_name' => 'fi_protie_garbagetruck_area_dba',
),
array
(
    'table' => 'fi_protie_garbagetruck_route',
    'old_class_name' => null,
    'new_class_name' => 'fi_protie_garbagetruck_route_db',
    'midcom_class_name' => 'fi_protie_garbagetruck_route_dba',
),
array
(
    'table' => 'fi_protie_garbagetruck_vehicle',
    'old_class_name' => null,
    'new_class_name' => 'fi_protie_garbagetruck_vehicle_db',
    'midcom_class_name' => 'fi_protie_garbagetruck_vehicle_dba',
),
array
(
    'table' => 'fi_protie_garbagetruck_log',
    'old_class_name' => null,
    'new_class_name' => 'fi_protie_garbagetruck_log_db',
    'midcom_class_name' => 'fi_protie_garbagetruck_log_dba',
),
