'default' => array
(
    'name' => 'default',
    'description' => 'person schema',
    'fields' => array
    (
        'firstname' => array
        (
            'title' => 'firstname',
            'storage' => 'firstname',
            'type' => 'text',
            'widget' => 'text',
        ),
        'lastname' => array
        (
            'title' => 'lastname',
            'storage' => 'lastname',
            'type' => 'text',
            'widget' => 'text',
        ),
    ),
),