'vehicle' => array
(
    'name' => 'truck',
    'description' => 'vehicle',
    'fields' => array
    (
        'name' => array
        (
            'title' => 'name',
            'storage' => 'name',
            'type' => 'text',
            'widget' => 'text',
        ),
        'regno' => array
        (
            'title' => 'registration id',
            'storage' => 'regno',
            'type' => 'text',
            'widget' => 'text',
        ),
    ),
),