'name' => 'org.openpsa.imp',
'purecode' => false,
'privileges' =>  Array(),
'class_definitions' => Array(),
'version' => '1.0.1',
'state' => 'stable',
'package.xml' => Array(
    'summary' => 'MidCOM-Horde/Imp "SSO"',
    'description' => 'Sort of Single Sign-On from MidCOM to Horde/Imp, works also with Squirrelmail (and possibly some others)',
    'maintainers' => Array(
        'rambo' => Array(
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
        'midcom.helper.datamanager' => Array(),
    ),
),
