
  'name' => 'org.openpsa.imp',
  'purecode' => false,
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'version' => '1.0.3beta1',
  'state' => 'beta',
  'package.xml' => 
  array (
    'summary' => 'MidCOM-Horde/Imp "SSO"',
    'description' => 'Sort of Single Sign-On from MidCOM to Horde/Imp, works also with Squirrelmail (and possibly some others)',
    'maintainers' => 
    array (
      'rambo' => 
      array (
        'name' => 'Eero af Heurlin',
        'email' => 'eero.afheurlin@iki.fi',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
