array(
    'table' => 'org_openpsa_task',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_task',
    'midcom_class_name' => 'org_openpsa_projects_task'
),
array(
    'table' => 'org_openpsa_task_resource',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_task_resource',
    'midcom_class_name' => 'midcom_org_openpsa_task_resource'
),
array(
    'table' => 'org_openpsa_hour_report',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_hour_report',
    'midcom_class_name' => 'midcom_org_openpsa_hour_report'
),
array(
    'table' => 'org_openpsa_expense',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_expense',
    'midcom_class_name' => 'midcom_org_openpsa_expense'
),
array(
    'table' => 'org_openpsa_deliverable',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_deliverable',
    'midcom_class_name' => 'midcom_org_openpsa_deliverable'
),
array(
    'table' => 'org_openpsa_task_status',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_task_status',
    'midcom_class_name' => 'midcom_org_openpsa_task_status'
),