'object' => array
(
    'description' => 'object schema',
    'l10n_db'     => 'midgard.admin.asgard',
    'fields'      => array
    (
        'guid' => Array
        (
            // COMPONENT-REQUIRED
            'title' => 'guid',
            'storage' => 'guid',
            'type' => 'text',
            'widget' => 'text',
            'readonly' => 'true',
        ),
        'id' => Array
        (
            'title' => 'id',
            'storage' => 'id',
            'type' => 'number',
            'widget' => 'text',
            'readonly' => 'true',
        ),
    )
),