
  'name' => 'midcom.tests',
  'Description' => 'Libary and frontend to run MidCOM unittests.',
  'purecode' => false,
  'version' => '0.1.2beta1',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'license' => 'GPL',
    'maintainers' => 
    array (
      'tarjei' => 
      array (
        'name' => 'Tarjei Huse',
        'email' => 'tarjei@nu.no',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      'simpletest' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
  'state' => 'beta',
