'name' => 'org.openpsa.core',
'purecode' => true,
'privileges' =>  Array(),
'class_definitions' => Array(),
'version' => '2.0.2',
'package.xml' => Array(
    'summary' => 'OpenPsa core library',
    'description' => 'OpenPsa core library',
    'maintainers' => Array(
        'rambo' => Array(
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
        'bergie' => Array(
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),  
    ),
    'dependencies' => Array(
        'org.openpsa.helpers'   => Array(),
        'template_OpenPsa2'   => Array(),
        'net.nehmer.markdown'   => Array(),
    ),
),
