'name' => 'org.openpsa.core',
'purecode' => true,
'privileges' => array(),
'class_definitions' => array(),
'version' => '2.1.0beta1',
'state' => 'beta',
'package.xml' => array
(
    'summary' => 'OpenPsa core library',
    'description' => 'OpenPsa core library',
    'maintainers' => array
    (
        'rambo' => array
        (
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'org.openpsa.helpers' => array(),
        'template_OpenPsa2' => array(),
        'net.nehmer.markdown' => array(),
        'midcom' => array(),
    ),
),
