CREATE TABLE cc_kaktus_todo_item (
    id int(11) NOT NULL auto_increment,
    up int(11) NOT NULL default '0',
    topic int(11) NOT NULL default '0',
    title varchar(255) NOT NULL default '',
    deadline datetime NOT NULL default '0000-00-00 00:00:00',
    description text NOT NULL default '',
    flag int(11) NOT NULL default 0,
    status int(11) NOT NULL default 0,
    pid int(11) NOT NULL default '',
    gid int(11) NOT NULL default '',
    guid varchar(80) NOT NULL default '',
    priority int(11) NOT NULL default 0,
    sitegroup int(11) NOT NULL default '0',
    score int(11) NOT NULL default '0',
    created int(11) NOT NULL default '0',
    creator int(11) NOT NULL default '0',
    revised int(11) NOT NULL default '0',
    revisor int(11) NOT NULL default '0',
    revision int(11) NOT NULL default '0',
    metadata_creator varchar(80) NOT NULL default '',
    metadata_created datetime NOT NULL default '0000-00-00 00:00:00',
    metadata_revisor varchar(80) NOT NULL default '',
    metadata_revised datetime NOT NULL default '0000-00-00 00:00:00',
    metadata_revision int(11) NOT NULL default '0',
    metadata_locker varchar(80) NOT NULL default '',
    metadata_locked datetime NOT NULL default '0000-00-00 00:00:00',
    metadata_approver varchar(80) NOT NULL default '',
    metadata_approved datetime NOT NULL default '0000-00-00 00:00:00',
    metadata_author varchar(80) NOT NULL default '',
    metadata_owner varchar(80) NOT NULL default '',
    metadata_schedule_start datetime NOT NULL default '0000-00-00 00:00:00',
    metadata_schedule_end datetime NOT NULL default '0000-00-00 00:00:00',
    metadata_hidden tinyint(1) default '0',
    metadata_nav_noentry tinyint(1) default '0',
    metadata_size int(11) NOT NULL default '0',
    metadata_score int(11) default '0',
    key cc_kaktus_todo_item_topic_idx(topic),
    key cc_kaktus_todo_item_sitegroup_idx(sitegroup),
    key cc_kaktus_todo_item_person_idx(pid),
    key cc_kaktus_todo_item_grp_idx(gid),
    primary key (id)
);