array(
    'table' => 'org_openpsa_salesproject',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_salesproject',
    'midcom_class_name' => 'midcom_org_openpsa_salesproject'
),
array(
    'table' => 'org_openpsa_salesproject_member',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_salesproject_member',
    'midcom_class_name' => 'midcom_org_openpsa_salesproject_member'
),
array(
    'table' => 'org_openpsa_salesproject_deliverable',
    'old_class_name' => null,
    'new_class_name' => 'org_openpsa_salesproject_deliverable',
    'midcom_class_name' => 'org_openpsa_sales_salesproject_deliverable'
),

