'name' => 'de.linkm.newsticker',
'version' => '2.5.1',
'state' => 'stable',
'package.xml' => Array(
    'summary' => 'News listing and blogging component',
    'description' => 'Component for posting news items and blogs. Supports RSS feeds, Podcasting and the MetaWeblog API',
    'maintainers' => Array(
        'midgard' => Array(
            'name' => 'The Midgard Project',
            'email' => 'dev@midgard-project.org',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
        'midcom.helper.datamanager' => Array(),
        'midcom.admin.content' => Array(),        
    ),
),
