'name' =>'no.bergfald.objectbrowser',
'purecode' => true,
'version' => '0.5.0',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(  
    'license' => 'GPL',  
    'maintainers' => Array( 
        'tarjei' => Array(  
            'name' => 'Tarjei Huse',  
            'email' => 'tarjei@nu.no',  
            'role' => 'lead',  
        ),  
    ),  
    'dependencies' => Array(
    
    'midcom.helper.datamanager' => Array(),
    'midcom.helper.datamanager2' => Array(),
    
    ),  
),

