'midgard_member' => array (
    'hide' => 1,
    'name_attribute_attribute' => '',
    ), 
'midgard_group' => array (
    'hide' => 1,
    'name_attribute_attribute' => '',
    ), 

'midcom_core_privilege_db' => array (
    'hide' => 1,
    'name_attribute' => '',
),
'midcom_core_login_session_db' => array (
    'hide' => 1,
    'name_attribute' => '',
),
'midcom_core_login_session' => array (
    'hide' => 1,
    'name_attribute' => '',
),
'midgard_attachment' => array (
    'hide' => 1,
    'name_attribute' => '',
),
'midgard_parameter' => array (
    'hide' => 1,
    'name_attribute' => array('domain', 'name'),
),
'midgard_page' => array (
    'hide' => 0,
    'name' => 'Pages',
    'name_attribute' => array('name'),
),
'midgard_event' => array (
    'hide' => 0,
    'name' => 'Events',
),
'midgard_topic' => array (
    'hide' => 0,
    'name' => 'Topics and articles',
),

'midgard_snippet' => array (
    'hide' => 0,
    'name' => 'Snippets',
),
'midgard_host' => array (
    'hide' => 0,
    'name' => 'Host',
    'name_attribute' => array ('name', 'prefix'), 
),
'midgard_person' => array (
    'hide' => 0,
    'name' => 'Person',
    'name_attribute' => array ('username'),
),