'name' => 'fi.hut.loginbroker',
'purecode' => false,
'version' => '0.9.5',
'state' => 'beta',
'privileges' => array (),
'class_definitions' => array (),
'package.xml' => array
(
    'license' => 'GPL',
    'summary' => 'Login broker',
    'description' => 'Broker logins from Shibboleth and similar systems to MidCOM sessions',
    'maintainers' => array
    (
        'rambo' => array
        (
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@nemein.com',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
