'name' => 'midcom.admin.content',
'purecode' => false,
'version' => '2.5.4',
'state' => 'stable',
'privileges' =>  Array
(
	'topic_management' => MIDCOM_PRIVILEGE_DENY,
),
'class_definitions' => Array(),
'package.xml' => Array(
    'summary' => 'MidCOM site management',
    'description' => 'Manage the directory structure and configuration of your MidCOM site',
    'maintainers' => Array(
        'midgard' => Array(
            'name' => 'The Midgard Project',
            'email' => 'dev@midgard-project.org',
            'role' => 'lead',
        ),
    ),
),
