array(
    'table' => 'org_openpsa_campaign',
    'mgdschema_class_name' => 'org_openpsa_campaign',
    'midcom_class_name' => 'midcom_org_openpsa_campaign'
),
array(
    'table' => 'org_openpsa_campaign_member',
    'mgdschema_class_name' => 'org_openpsa_campaign_member',
    'midcom_class_name' => 'midcom_org_openpsa_campaign_member'
),
array(
    'table' => 'org_openpsa_campaign_message',
    'mgdschema_class_name' => 'org_openpsa_campaign_message',
    'midcom_class_name' => 'midcom_org_openpsa_campaign_message'
),
array(
    'table' => 'org_openpsa_campaign_message_receipt',
    'mgdschema_class_name' => 'org_openpsa_campaign_message_receipt',
    'midcom_class_name' => 'midcom_org_openpsa_campaign_message_receipt'
),
array(
    'table' => 'org_openpsa_link_log',
    'mgdschema_class_name' => 'org_openpsa_link_log',
    'midcom_class_name' => 'midcom_org_openpsa_link_log'
)