
  'name' => 'midcom.admin.settings',
  'description' => 'This module handles MidCOM local configuration.',
  'purecode' => true,
  'version' => '0.1.5beta1',
  'state' => 'beta',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'license' => 'LGPL',
    'maintainers' => 
    array (
      'solt' => 
      array (
        'name' => 'Marcin Sołtysiak',
        'email' => 'olga@olga.pl',
        'role' => 'lead',
      ),
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'developer',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager2' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
