'name' => 'org.openpsa.notifications',
'purecode' => true,
'privileges' =>  Array(),
'class_definitions' => Array(),
'version' => '0.0.1',
'package.xml' => Array(
    'summary' => 'Notification manager',
    'description' => 'System for sending notifications to users based on their preferences',
    'maintainers' => Array(
        'bergie' => Array(
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),  
    ),
    'dependencies' => Array(
        'org.openpsa.mail'          => Array(),
    ),
),
