'name' => 'midcom.helper.xsspreventer',
'purecode' => true,
'privileges' => array(),
'class_definitions' => array(),
'version' => '1.0.0',
'state' => 'stable',
'package.xml' => array
(
    'summary' => 'Library for escaping user provided values',
    'description' => 'Library for escaping user provided values displayed for example in input etc',
    'maintainers' => array
    (
        'rambo' => array
        (
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
        'tepheik' => array
        (
            'name' => 'Tero Heikkinen',
            'email' => 'tero.heikkinen@rohea.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
