'name' => 'net.nemein.personnel',
'purecode' => false,
'version' => '1.0.0beta',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(
    'summary' => 'Personnel listing',
    'description' => 'Component to display persons in group',
    'maintainers' => Array(
        'bergie' => Array(
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
        'torben' => Array(
            'name' => 'Torben Nehmer',
            'email' => 'torben@nehmer.net',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
        'midcom.helper.datamanager2' => Array(),
    ),
),
