'name' => 'net.nemein.personnel',
'purecode' => false,
'version' => '1.0.2beta1',
'state' => 'beta',
'privileges' => array (),
'class_definitions' => array (),
'package.xml' => array
(
    'summary' => 'Personnel listing',
    'description' => 'Component to display persons in group',
    'maintainers' => array
    (
      'bergie' => array
      (
          'name' => 'Henri Bergius',
          'email' => 'henri.bergius@iki.fi',
          'role' => 'lead',
          'active' => 'yes',
      ),
      'torben' => array
      (
          'name' => 'Torben Nehmer',
          'email' => 'torben@nehmer.net',
          'role' => 'lead',
          'active' => 'no',
      ),
      'adrenalin' => array
      (
          'name' => 'Arttu Manninen',
          'email' => 'arttu.manninen@protie.fi',
          'role' => 'lead',
          'active' => 'yes',
      ),
      'tarjei' => array
      (
          'name' => 'Tarje Huse',
          'email' => 'tarjei@nu.no',
          'role' => 'lead',
          'active' => 'yes',
      ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => array (),
        'midcom' => array (),
    ),
),
