'name' => 'midcom.admin.help',
'description' => 'This module handles help.',
'purecode' => true,
'version' => '0.0.1',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(
    'license' => 'GPL',
    'maintainers' => Array(
        'tarjei' => Array(
            'name' => 'Tarjei Huse',
            'email' => 'tarjei@nu.no',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
    ),
),
