'name' => 'midcom.admin.help',
'icon' => 'stock-icons/16x16/stock_help-agent.png',
'description' => 'On-site help displayer',
'purecode' => true,
'version' => '1.1.0beta1',
'state' => 'beta',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'license' => 'GPL',
    'maintainers' => array
    (
        'tarjei' => array
        (
            'name' => 'Tarjei Huse',
            'email' => 'tarjei@nu.no',
            'role' => 'lead',
        ),
        'adrenalin' => array
        (
            'name' => 'Arttu Manninen',
            'email' => 'arttu@kaktus.cc',
            'role' => 'developer',
        ),
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'developer',
        ),
    ),
    'dependencies' => array
    (
        'net.nehmer.markdown' => array(),
        'midcom' => array(),
    ),
),
