
  'name' => 'midcom.admin.help',
  'description' => 'On-site help displayer',
  'purecode' => true,
  'version' => '1.0.2beta1',
  'state' => 'beta',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'license' => 'GPL',
    'maintainers' => 
    array (
      'tarjei' => 
      array (
        'name' => 'Tarjei Huse',
        'email' => 'tarjei@nu.no',
        'role' => 'lead',
      ),
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'developer',
      ),
    ),
    'dependencies' => 
    array (
      'net.nehmer.markdown' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
