
  'name' => 'net.siriux.photos',
  'version' => '1.0.3beta1',
  'package.xml' => 
  array (
    'summary' => 'Photo Gallery',
    'description' => 'Photo Gallery',
    'maintainers' => 
    array (
      'torben' => 
      array (
        'name' => 'Torben Nehmer',
        'email' => 'torben@nehmer.net',
        'role' => 'lead',
        'active' => 'no',
      ),
    ),
    'dependencies' => 
    array (
      'midcom.helper.datamanager' => 
      array (
      ),
      'midcom' => 
      array (
      ),
    ),
  ),
  'state' => 'beta',
