'name' => 'net.nemein.flashplayer',
'purecode' => true,
'version' => '1.0.0',
'state' => 'stable',
'privileges' => array (),
'class_definitions' => array (),
'package.xml' => array
(
    'summary' => 'Flash player and playlist',
    'description' => 'Player and playlist for flash videos and photos',
    'maintainers' => array
    (
        'bergie' => array
        (
            'name' => 'Jerry Jalava',
            'email' => 'jerry.jalava@gmail.com',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array (),
),
