'name' => 'net.nemein.flashplayer',
'purecode' => true,
'version' => '1.1.0beta1',
'state' => 'beta',
'privileges' => array(),
'class_definitions' => array(),
'package.xml' => array
(
    'summary' => 'Flash player and playlist',
    'description' => 'Player and playlist for flash videos and photos',
    'maintainers' => array
    (
        'w_i' => array
        (
            'name' => 'Jerry Jalava',
            'email' => 'jerry.jalava@gmail.com',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array(),
),
