'name' => 'midcom.admin.styleeditor',
'description' => 'A MidCom based editor for midgard styles',
'purecode' => true,
'version' => "0.1.0",
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(  
    'license' => 'GPL',  
    'maintainers' => Array( 
        'tarjei' => Array(  
            'name' => 'Tarjei Huse',  
            'email' => 'tarjei@nu.no',  
            'role' => 'lead',  
        ),  
    ),  
    'dependencies' => Array(
    'midcom.admin.aegir' => array(),
    'midcom.admin.content2' => array(),
    'no.bergfald.rcs' => array(),
    'midcom.helper.datamanager2' => Array(),
    ),  
),
