
  'name' => 'midcom.admin.styleeditor',
  'description' => 'Style editor for Midgard style templates',
  'purecode' => true,
  'version' => '0.2.2beta1',
  'privileges' => 
  array (
  ),
  'class_definitions' => 
  array (
  ),
  'package.xml' => 
  array (
    'license' => 'LGPL',
    'maintainers' => 
    array (
      'adrenalin' => 
      array (
        'name' => 'Arttu Manninen',
        'email' => 'arttu.manninen@protie.fi',
        'role' => 'lead',
      ),
      'bergie' => 
      array (
        'name' => 'Henri Bergius',
        'email' => 'henri.bergius@iki.fi',
        'role' => 'lead',
      ),
    ),
    'dependencies' => 
    array (
      0 => 'midcom.admin.help',
      'midcom' => 
      array (
      ),
    ),
  ),
  'state' => 'beta',
