
'style' => Array
(
    'description' => 'Midcom Style element',
    'fields' => Array
    (
        'name' => Array
        (
            'title' => 'Name',
            'description' => 'fieldname ',
            'helptext' => '',
            'storage' => 'name',
            'required' => true,
            'type' => 'text',
            'widget' => 'text',
        ),
    
   'value' => Array
     (
            'title' => 'This is where the code goes',
            'description' => '',
            'helptext' => '',
            'storage' => 'value',
            'type' => 'text',
            'widget' => 'textarea',
            'widget_config' => array ('expand' => true),
            
    ),
    
    ), // fields
    
),