
'style' => Array
(
    'description' => 'Midcom Style element',
    'fields' => Array
    (
        'name' => Array
        (
            'title' => 'Name',
            'description' => 'fieldname ',
            'helptext' => '',
            'storage' => 'name',
            'required' => true,
            'type' => 'text',
            'widget' => 'text',
        ),
    'guid' => Array
     (
            'title' => 'Component ID',
            'description' => 'This is the Global ID (GUID) of this object',
            'helptext' => '',
            'storage' => 'guid',
            'type' => 'text',
            'widget' => 'text',
            'readonly' => true,
    ),
   'value' => Array
     (
            'title' => 'This is where the code goes',
            'description' => '',
            'helptext' => '',
            'storage' => 'value',
            'type' => 'text',
            'widget' => 'textarea',
            
    ),
    
    ), // fields
    
),