'name' => 'org.openpsa.mypage',
'purecode' => false,
'privileges' =>  Array(),
'class_definitions' => Array(),
'version' => '2.0.2',
'package.xml' => Array(
    'summary' => 'OpenPSA summary page',
    'description' => 'At a glance view of your documents, tasks etc',
    'maintainers' => Array(
        'bergie' => Array(
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),  
    ),
    'dependencies' => Array(
        'org.openpsa.core'          => Array(),
        'org.openpsa.helpers'       => Array(),
        'midcom.helper.datamanager' => Array(),
        'org.openpsa.contactwidget' => Array(),
    ),
),
