'name' => 'midcom.helper.dm2config',
'version' => '0.1.0beta1',
'state' => 'beta',
'purecode' => true,
'package.xml' => array
(
    'summary' => 'midcom.helper.datamanager2 based configuration',
    'description' => 'midcom.helper.datamanager2 based configuration interface to boost up configuration with modern widgets',
    'state' => 'alpha',
    'maintainers' => array
    (
        'adrenalin' => array
        (
            'name' => 'Arttu Manninen',
            'email' => 'arttu@kaktus.cc',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => array(),
    ),
),
