'name'              => 'net.nemein.favourites',
'icon'              => 'net.nemein.favourites/favorite.png',
'purecode'          => false,
'version'           => '1.0.0beta2',
'state'             => 'beta',
'privileges'        => Array(),
'class_definitions' => Array('midcom_dba_classes.inc'),
'watches'           => Array(),
'package.xml' => Array
(  
    'license' => 'GPL', 
    'summary' => 'Favourites',
    'description' => 'Favourites listing',
    'maintainers' => Array
    ( 
        'juhana' => Array
        (  
	       'name' => 'Juhana Hirvilahti',  
    	    'email' => 'juhana@nemein.com',  
    	    'role' => 'lead',  
    	 ),
         'W_I' => Array
         (  
            'name' => 'Jerry Jalava',  
     	    'email' => 'jerry.jalava@gmail.com',  
     	    'role' => 'lead',  
     	 ),
     ),
),
