'name' => 'net.nemein.favourites',
'icon' => 'net.nemein.favourites/favorite.png',
'purecode' => false,
'version' => '1.1.0beta1',
'state' => 'beta',
'privileges' => array(),
'class_definitions' => array
(
    'midcom_dba_classes.inc',
),
'watches' => array(),
'package.xml' => array
(
    'license' => 'GPL',
    'summary' => 'Favourites',
    'description' => 'Favourites listing',
    'maintainers' => array
    (
        'juhana' => array
        (
            'name' => 'Juhana Hirvilahti',
            'email' => 'juhana@nemein.com',
            'role' => 'lead',
        ),
        'w_i' => array
        (
            'name' => 'Jerry Jalava',
            'email' => 'jerry.jalava@gmail.com',
            'role' => 'lead',
        ),
    ),
),
