Array
(
    'table' => 'midcom_core_temporary_object_db',
    'mgdschema_class_name' => 'midcom_core_temporary_object_db',
    'midcom_class_name' => 'midcom_core_temporary_object'
),
// We need these for the replicator to be able to instantiate them...
Array
(
    'table' => 'midcom_group_virtual',
    'mgdschema_class_name' => 'midcom_core_group_virtual_db',
    'midcom_class_name' => 'midcom_core_group_virtual_dba'
),
Array
(
    'table' => 'midcom_core_privilege',
    'mgdschema_class_name' => 'midcom_core_privilege_db',
    'midcom_class_name' => 'midcom_core_privilege_dba'
),
