Array
(
    'table' => 'article',
    'old_class_name' => null,
    'new_class_name' => 'midgard_article',
    'midcom_class_name' => 'midcom_baseclasses_database_article'
),
Array
(
    'table' => 'blobs',
    'old_class_name' => null,
    'new_class_name' => 'midgard_attachment',
    'midcom_class_name' => 'midcom_baseclasses_database_attachment'
),
Array
(
    'table' => 'element',
    'old_class_name' => null,
    'new_class_name' => 'midgard_element',
    'midcom_class_name' => 'midcom_baseclasses_database_element'
),
Array
(
    'table' => 'event',
    'old_class_name' => null,
    'new_class_name' => 'midgard_event',
    'midcom_class_name' => 'midcom_baseclasses_database_event'
),
Array
(
    'table' => 'eventmember',
    'old_class_name' => null,
    'new_class_name' => 'midgard_eventmember',
    'midcom_class_name' => 'midcom_baseclasses_database_eventmember'
),
Array
(
    'table' => 'grp',
    'old_class_name' => null,
    'new_class_name' => 'midgard_group',
    'midcom_class_name' => 'midcom_baseclasses_database_group'
),
Array
(
    'table' => 'host',
    'old_class_name' => null,
    'new_class_name' => 'midgard_host',
    'midcom_class_name' => 'midcom_baseclasses_database_host'
),
Array
(
    'table' => 'language',
    'old_class_name' => null,
    'new_class_name' => 'midgard_language',
    'midcom_class_name' => 'midcom_baseclasses_database_language'
),
Array
(
    'table' => 'member',
    'old_class_name' => null,
    'new_class_name' => 'midgard_member',
    'midcom_class_name' => 'midcom_baseclasses_database_member'
),
Array
(
    'table' => 'page',
    'old_class_name' => null,
    'new_class_name' => 'midgard_page',
    'midcom_class_name' => 'midcom_baseclasses_database_page'
),
Array
(
    'table' => 'pageelement',
    'old_class_name' => null,
    'new_class_name' => 'midgard_pageelement',
    'midcom_class_name' => 'midcom_baseclasses_database_pageelement'
),
Array
(
    'table' => 'record_extension',
    'old_class_name' => null,
    'new_class_name' => 'midgard_parameter',
    'midcom_class_name' => 'midcom_baseclasses_database_parameter'
),
Array
(
    'table' => 'person',
    'old_class_name' => null,
    'new_class_name' => 'midgard_person',
    'midcom_class_name' => 'midcom_baseclasses_database_person'
),
Array
(
    'table' => 'snippet',
    'old_class_name' => null,
    'new_class_name' => 'midgard_snippet',
    'midcom_class_name' => 'midcom_baseclasses_database_snippet'
),
Array
(
    'table' => 'snippetdir',
    'old_class_name' => null,
    'new_class_name' => 'midgard_snippetdir',
    'midcom_class_name' => 'midcom_baseclasses_database_snippetdir'
),
Array
(
    'table' => 'style',
    'old_class_name' => null,
    'new_class_name' => 'midgard_style',
    'midcom_class_name' => 'midcom_baseclasses_database_style'
),
Array
(
    'table' => 'topic',
    'old_class_name' => null,
    'new_class_name' => 'midgard_topic',
    'midcom_class_name' => 'midcom_baseclasses_database_topic'
),
