'name' => 'de.linkm.taviewer',
'version' => '2.5.1',
'state' => 'stable',
'package.xml' => Array(
    'summary' => 'Static article content display',
    'description' => 'Static content display component emulating regular directory of HTML files',
    'maintainers' => Array(
        'midgard' => Array(
            'name' => 'The Midgard Project',
            'email' => 'dev@midgard-project.org',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
        'midcom.helper.datamanager' => Array(),
        'midcom.admin.content' => Array(),
    ),
),

