'name' => 'de.bitfolge.feedcreator',
'purecode' => true,
'version' => '1.7.7',
'state'   => 'stable',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(
    'summary' => 'News feed generator',
    'description' => 'RSS and Atom feed generator by Kai Blankenhorn',
    'maintainers' => Array(
        'bergie' => Array(
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => Array(
    ),
),
