'schemadb_person' => 'file:/midcom/admin/user/config/schemadb_person.inc',
'schemadb_group' => 'file:/midcom/admin/user/config/schemadb_group.inc',
'list_without_search' => 20,
'allow_manage_accounts' => true, // Turn this off if the accounts are integrated with some external source like AD or LDAP
'search_fields' => array
(
    'firstname',
    'lastname',
    'username',
    'email',
    'city',
    'postcode',    
),
'list_fields' => array
(
    'firstname',
    'lastname',
    'username',
    'email',
    'city', 
),