'name' => 'midcom.admin.parameters',
'description' => 'This module handles the administration of parameters.',
'purecode' => true,
'version' => '0.7.0',
'privileges' =>  Array(),
'class_definitions' => Array(),
'package.xml' => Array(  
    'license' => 'GPL',  
    'maintainers' => Array( 
        'tarjei' => Array(  
            'name' => 'Tarjei Huse',  
            'email' => 'tarjei@nu.no',  
            'role' => 'lead',  
        ),  
    ),  
    'dependencies' => Array(
    'midcom.admin.aegir' => array(),
    'midcom.helper.datamanager2' => Array(),
    ),  
),
