'name' => 'midgard.admin.acl',
'purecode' => true,
'privileges' => array(),
'class_definitions' => array(),
'version' => '1.1.0beta1',
'state' => 'beta',
'package.xml' => array
(
    'summary' => 'ACL editor',
    'description' => 'Tool for editing Access Control Lists',
    'maintainers' => array
    (
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
            'active' => 'no',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => array(),
        'midcom' => array(),
    ),
),
